# Generated by Django 5.0.6 on 2025-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True, verbose_name='\x18<O AB@0=8FK')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Title (RU)')),
                ('description_ru', models.TextField(blank=True, max_length=300, verbose_name='Description (RU)')),
                ('keywords_ru', models.TextField(blank=True, verbose_name='Keywords (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Title (EN)')),
                ('description_en', models.TextField(blank=True, max_length=300, verbose_name='Description (EN)')),
                ('keywords_en', models.TextField(blank=True, verbose_name='Keywords (EN)')),
                ('title_th', models.CharField(blank=True, max_length=200, verbose_name='Title (TH)')),
                ('description_th', models.TextField(blank=True, max_length=300, verbose_name='Description (TH)')),
                ('keywords_th', models.TextField(blank=True, verbose_name='Keywords (TH)')),
                ('is_active', models.BooleanField(default=True, verbose_name='\x10:B82=>')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='!>740=>')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\x1e1=>2;5=>')),
            ],
            options={
                'verbose_name': 'SEO AB@0=8F0',
                'verbose_name_plural': 'SEO AB@0=8FK',
            },
        ),
    ]
