# Generated by Django 5.0.6 on 2025-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seotemplate_alter_seopage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seotemplate',
            name='deal_type',
            field=models.CharField(blank=True, choices=[('', '-- Все типы сделок --'), ('sale', 'Продажа'), ('rent', 'Аренда'), ('both', 'Продажа/Аренда')], help_text='Выберите тип сделки или оставьте пустым для всех типов', max_length=20, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='seotemplate',
            name='property_type',
            field=models.CharField(blank=True, choices=[('', '-- Все типы --'), ('villa', 'Вилла'), ('apartment', 'Апартаменты'), ('townhouse', 'Таунхаус'), ('land', 'Земельный участок'), ('investment', 'Инвестиции'), ('business', 'Готовый бизнес')], help_text='Выберите тип недвижимости или оставьте пустым для всех типов', max_length=50, verbose_name='Тип недвижимости'),
        ),
    ]
