# Generated by Django 5.0.6 on 2025-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promotionalbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalbanner',
            name='button_text_en',
            field=models.CharField(blank=True, help_text='Например: "Узнать подробнее" или "Связаться с нами"', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='button_text_ru',
            field=models.CharField(blank=True, help_text='Например: "Узнать подробнее" или "Связаться с нами"', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='button_text_th',
            field=models.CharField(blank=True, help_text='Например: "Узнать подробнее" или "Связаться с нами"', max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='description_th',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='discount_text_en',
            field=models.CharField(blank=True, help_text='Например: "Скидка 20%" или "Ограниченное предложение"', max_length=100, null=True, verbose_name='Текст скидки/предложения'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='discount_text_ru',
            field=models.CharField(blank=True, help_text='Например: "Скидка 20%" или "Ограниченное предложение"', max_length=100, null=True, verbose_name='Текст скидки/предложения'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='discount_text_th',
            field=models.CharField(blank=True, help_text='Например: "Скидка 20%" или "Ограниченное предложение"', max_length=100, null=True, verbose_name='Текст скидки/предложения'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='title_th',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image',
            field=models.ImageField(help_text='Рекомендуемое разрешение: 1248x125 пикселей', upload_to='promotional_banners/', verbose_name='Фоновое изображение'),
        ),
    ]
