# Generated by Django 5.0.6 on 2025-07-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_promotionalbanner_button_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный URL адрес страницы (например: buying-property)', max_length=100, unique=True, verbose_name='URL-адрес')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_th', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(help_text='Краткое описание услуги для превью', max_length=500, verbose_name='Краткое описание')),
                ('description_ru', models.TextField(help_text='Краткое описание услуги для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('description_en', models.TextField(help_text='Краткое описание услуги для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('description_th', models.TextField(help_text='Краткое описание услуги для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Подробное описание услуги', verbose_name='Основной контент')),
                ('content_ru', models.TextField(help_text='Подробное описание услуги', null=True, verbose_name='Основной контент')),
                ('content_en', models.TextField(help_text='Подробное описание услуги', null=True, verbose_name='Основной контент')),
                ('content_th', models.TextField(help_text='Подробное описание услуги', null=True, verbose_name='Основной контент')),
                ('meta_title', models.CharField(blank=True, help_text='Если пустое, будет использоваться основной заголовок', max_length=200, verbose_name='SEO заголовок')),
                ('meta_title_ru', models.CharField(blank=True, help_text='Если пустое, будет использоваться основной заголовок', max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_en', models.CharField(blank=True, help_text='Если пустое, будет использоваться основной заголовок', max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_th', models.CharField(blank=True, help_text='Если пустое, будет использоваться основной заголовок', max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, help_text='Если пустое, будет использоваться краткое описание', max_length=300, verbose_name='SEO описание')),
                ('meta_description_ru', models.TextField(blank=True, help_text='Если пустое, будет использоваться краткое описание', max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_en', models.TextField(blank=True, help_text='Если пустое, будет использоваться краткое описание', max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_th', models.TextField(blank=True, help_text='Если пустое, будет использоваться краткое описание', max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_ru', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_en', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_th', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('image', models.ImageField(blank=True, help_text='Основное изображение для страницы услуги', upload_to='services/', verbose_name='Изображение')),
                ('icon_class', models.CharField(blank=True, help_text='CSS класс для иконки в меню (например: fas fa-home)', max_length=100, verbose_name='CSS класс иконки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('menu_order', models.IntegerField(default=100, help_text='Порядок отображения в меню (меньше = выше)', verbose_name='Порядок в меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['menu_order', 'title'],
            },
        ),
    ]
