# Generated by Django 5.0.6 on 2025-10-10 07:21

from django.db import migrations, models


def copy_banner_media_forward(apps, schema_editor):
    PromotionalBanner = apps.get_model('core', 'PromotionalBanner')

    for banner in PromotionalBanner.objects.all():
        source_image = getattr(banner, 'image', None)
        button_url = getattr(banner, 'button_url', '')

        updated_fields = []

        if source_image and not banner.desktop_image:
            banner.desktop_image = source_image
            updated_fields.append('desktop_image')

        if source_image and not banner.tablet_image:
            banner.tablet_image = source_image
            updated_fields.append('tablet_image')

        if source_image and not banner.mobile_image:
            banner.mobile_image = source_image
            updated_fields.append('mobile_image')

        if button_url and not banner.link:
            banner.link = button_url
            updated_fields.append('link')

        if updated_fields:
            banner.save(update_fields=updated_fields)


def copy_banner_media_backward(apps, schema_editor):
    PromotionalBanner = apps.get_model('core', 'PromotionalBanner')

    for banner in PromotionalBanner.objects.all():
        fallback_image = banner.desktop_image or banner.tablet_image or banner.mobile_image
        updated_fields = []

        if fallback_image and hasattr(banner, 'image'):
            banner.image = fallback_image
            updated_fields.append('image')

        if hasattr(banner, 'button_url'):
            banner.button_url = banner.link
            updated_fields.append('button_url')

        if updated_fields:
            banner.save(update_fields=updated_fields)


def set_language_default_forward(apps, schema_editor):
    PromotionalBanner = apps.get_model('core', 'PromotionalBanner')
    PromotionalBanner.objects.filter(language_code__isnull=True).update(language_code='ru')


def set_language_default_backward(apps, schema_editor):
    PromotionalBanner = apps.get_model('core', 'PromotionalBanner')
    PromotionalBanner.objects.update(language_code='ru')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_team_facebook_team_instagram_team_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionalbanner',
            options={'verbose_name': 'Рекламный баннер', 'verbose_name_plural': 'Рекламные баннеры'},
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='language_code',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('th', 'Тайский')], default='ru', help_text='Создавайте отдельные баннеры для каждого языка (RU / EN / TH).', max_length=2, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='desktop_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 2400×150 px. Держите ключевой контент в центральной зоне, края могут обрезаться.', upload_to='promotional_banners/', verbose_name='Изображение для десктопа'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='link',
            field=models.CharField(blank=True, help_text='Полный URL (https://example.com), путь с языковым префиксом (/ru/path/) или имя Django URL pattern.', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 828×150 px. Располагайте текст и логотип внутри центральных 60% ширины.', upload_to='promotional_banners/', verbose_name='Изображение для мобильных устройств'),
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='tablet_image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 1536×150 px. Фокусируйте основной контент в центре кадра.', upload_to='promotional_banners/', verbose_name='Изображение для планшета'),
        ),
        migrations.RunPython(set_language_default_forward, set_language_default_backward),
        migrations.RunPython(copy_banner_media_forward, copy_banner_media_backward),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='promotionalbanner',
            name='valid_until',
        ),
        migrations.DeleteModel(
            name='PromotionalBannerTranslation',
        ),
    ]
