# Generated by Django 5.0.6 on 2025-10-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_promotionalbanner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionalbanner',
            options={'ordering': ['language_code', 'id'], 'verbose_name': 'Рекламный баннер', 'verbose_name_plural': 'Рекламные баннеры'},
        ),
    ]
