# Generated by Django 5.0.6 on 2025-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_promotionalbanner_language_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionalbanner',
            options={'ordering': ['language_code', 'name'], 'verbose_name': 'Рекламный баннер', 'verbose_name_plural': 'Рекламные баннеры'},
        ),
        migrations.AddField(
            model_name='promotionalbanner',
            name='name',
            field=models.CharField(default='', help_text='Внутреннее имя, чтобы не путаться между акциями в админке', max_length=150, verbose_name='Название баннера'),
        ),
    ]
