# Generated by Django 5.0.6 on 2026-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_team_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('client_ip', models.GenericIPAddressField(verbose_name='IP клиента')),
                ('proxy_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP прокси')),
                ('method', models.CharField(max_length=10, verbose_name='Метод')),
                ('path', models.CharField(max_length=2048, verbose_name='Путь')),
                ('referer', models.CharField(blank=True, max_length=2048, verbose_name='Реферер')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP статус')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Заголовки')),
                ('bot_score', models.PositiveSmallIntegerField(default=0, verbose_name='Bot score')),
                ('matched_rules', models.JSONField(blank=True, default=list, verbose_name='Совпавшие правила')),
                ('action', models.CharField(choices=[('allow', 'Разрешить'), ('monitor', 'Наблюдать'), ('challenge', 'Проверка'), ('block', 'Блокировка')], default='allow', max_length=16, verbose_name='Действие')),
                ('source', models.CharField(choices=[('middleware', 'Middleware'), ('nginx', 'Парсер nginx'), ('management', 'Management команда')], default='middleware', max_length=16, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Лог антибот-защиты',
                'verbose_name_plural': 'Логи антибот-защиты',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['client_ip', 'created_at'], name='requestlog_ip_created_idx'), models.Index(fields=['bot_score'], name='requestlog_score_idx'), models.Index(fields=['action'], name='requestlog_action_idx')],
            },
        ),
    ]
