# Generated by Django 5.0.6 on 2025-06-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_th', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_th', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='developers/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_th', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('villa', 'Вилла'), ('apartment', 'Апартаменты'), ('condo', 'Кондоминиум'), ('townhouse', 'Таунхаус'), ('commercial', 'Коммерческая'), ('land', 'Земля')], max_length=20, unique=True, verbose_name='Тип')),
                ('name_display', models.CharField(max_length=50, verbose_name='Отображаемое название')),
                ('name_display_ru', models.CharField(max_length=50, null=True, verbose_name='Отображаемое название')),
                ('name_display_en', models.CharField(max_length=50, null=True, verbose_name='Отображаемое название')),
                ('name_display_th', models.CharField(max_length=50, null=True, verbose_name='Отображаемое название')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_th', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда'), ('both', 'Продажа/Аренда')], default='sale', max_length=10, verbose_name='Тип сделки')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('reserved', 'Забронировано'), ('sold', 'Продано'), ('rented', 'Сдано')], default='available', max_length=10, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_th', models.TextField(null=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('short_description_th', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('address_th', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Долгота')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Спальни')),
                ('bathrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ванные')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Общая площадь, м²')),
                ('area_living', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Жилая площадь, м²')),
                ('area_land', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь участка, м²')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('floors_total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего этажей')),
                ('price_sale_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена продажи, USD')),
                ('price_sale_thb', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена продажи, THB')),
                ('price_rent_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Аренда в месяц, USD')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('furnished', models.BooleanField(default=False, verbose_name='С мебелью')),
                ('pool', models.BooleanField(default=False, verbose_name='Бассейн')),
                ('parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('security', models.BooleanField(default=False, verbose_name='Охрана')),
                ('gym', models.BooleanField(default=False, verbose_name='Спортзал')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.developer', verbose_name='Застройщик')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.district', verbose_name='Район')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Локация')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFeatureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertyfeature')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'feature')},
            },
        ),
    ]
