# Generated by Django 5.0.6 on 2025-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('villa', 'Вилла'), ('apartment', 'Апартаменты'), ('townhouse', 'Таунхаус'), ('land', 'Земельный участок'), ('investment', 'Инвестиции'), ('business', 'Готовый бизнес')], max_length=20, unique=True, verbose_name='Тип'),
        ),
    ]
