# Generated by Django 5.0.6 on 2025-06-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertytype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='custom_description_en',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=300, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_description_ru',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=300, verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_description_th',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=300, verbose_name='Описание (TH)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_keywords_en',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', verbose_name='Ключевые слова (EN)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_keywords_ru',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', verbose_name='Ключевые слова (RU)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_keywords_th',
            field=models.TextField(blank=True, help_text='Оставьте пустым для автоматической генерации', verbose_name='Ключевые слова (TH)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_title_en',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=200, verbose_name='Заголовок (EN)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_title_ru',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=200, verbose_name='Заголовок (RU)'),
        ),
        migrations.AddField(
            model_name='property',
            name='custom_title_th',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=200, verbose_name='Заголовок (TH)'),
        ),
    ]
