# Generated by Django 5.0.6 on 2025-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_custom_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='architectural_style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Архитектурный стиль'),
        ),
        migrations.AddField(
            model_name='property',
            name='complex_name',
            field=models.CharField(blank=True, help_text='Название жилого комплекса или проекта', max_length=100, verbose_name='Название комплекса'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_airport',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До аэропорта, мин'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_beach',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До пляжа, мин'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_school',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='До школы, мин'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_potential',
            field=models.TextField(blank=True, help_text='Описание инвестиционной привлекательности', verbose_name='Инвестиционный потенциал'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_urgent_sale',
            field=models.BooleanField(default=False, verbose_name='Срочная продажа'),
        ),
        migrations.AddField(
            model_name='property',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Идентификатор из старой Joomla системы (например: VS82)', max_length=20, null=True, unique=True, verbose_name='ID старой системы'),
        ),
        migrations.AddField(
            model_name='property',
            name='material_type',
            field=models.CharField(blank=True, help_text='Основные строительные материалы', max_length=200, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='property',
            name='original_price_thb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена до скидки', max_digits=15, null=True, verbose_name='Первоначальная цена, THB'),
        ),
        migrations.AddField(
            model_name='property',
            name='pool_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь бассейна, м²'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_for',
            field=models.CharField(blank=True, help_text='Назначение использования (отпуск, постоянное проживание и т.д.)', max_length=200, verbose_name='Подходит для'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgency_note',
            field=models.CharField(blank=True, help_text='Дополнительная информация о срочной продаже', max_length=200, verbose_name='Примечание о срочности'),
        ),
    ]
