# Generated by Django 5.0.6 on 2025-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_architectural_style_property_complex_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_rent_monthly_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Аренда в месяц, RUB'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_rent_monthly_thb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Аренда в месяц, THB'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_sale_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена продажи, RUB'),
        ),
    ]
