# Generated by Django 5.0.6 on 2025-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_agent_property_double_beds_property_floorplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='name_display',
            field=models.CharField(max_length=100, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name_display_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name_display_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Отображаемое название'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name_display_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Отображаемое название'),
        ),
    ]
