# Generated by Django 5.0.6 on 2025-07-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_legacy_id'),
    ]

    operations = [
        # Добавляем поля для удобств (amenities) из дампа Joomla
        migrations.AddField(
            model_name='property',
            name='amenity_air_conditioning',
            field=models.BooleanField(default=False, help_text='Кондиционер', verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_kitchen',
            field=models.BooleanField(default=False, help_text='Кухня', verbose_name='Кухня'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_shower',
            field=models.BooleanField(default=False, help_text='Душ', verbose_name='Душ'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_wifi',
            field=models.BooleanField(default=False, help_text='WiFi', verbose_name='WiFi'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_free_parking',
            field=models.BooleanField(default=False, help_text='Бесплатная парковка', verbose_name='Бесплатная парковка'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_gated_community',
            field=models.BooleanField(default=False, help_text='Огороженная территория', verbose_name='Огороженная территория'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_pool',
            field=models.BooleanField(default=False, help_text='Бассейн', verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_bathtub',
            field=models.BooleanField(default=False, help_text='Ванна', verbose_name='Ванна'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenity_cctv',
            field=models.BooleanField(default=False, help_text='Видеонаблюдение', verbose_name='Видеонаблюдение'),
        ),
    ]
