# Generated by Django 5.0.6 on 2025-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_auto_20250709_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenity_air_conditioning',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_bathtub',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_cctv',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_free_parking',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_gated_community',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_kitchen',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_pool',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_shower',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenity_wifi',
        ),
    ]
