# Generated by Django 5.0.6 on 2025-07-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_remove_property_amenity_air_conditioning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=19, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('villa', 'Вилла'), ('condo', 'Кондоминиум'), ('townhouse', 'Таунхаус'), ('land', 'Земельный участок'), ('investment', 'Инвестиции'), ('business', 'Готовый бизнес')], max_length=20, unique=True, verbose_name='Тип'),
        ),
    ]
