# Generated by Django 5.0.6 on 2025-07-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_latitude_alter_property_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfeaturerelation',
            name='value',
        ),
    ]
