# Generated by Django 5.0.6 on 2025-08-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_remove_value_from_propertyfeaturerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_for_investment',
            field=models.BooleanField(default=False, help_text='Объект рекомендован для инвестиций', verbose_name='Для инвестиций'),
        ),
    ]
