# Generated by Django 5.0.6 on 2025-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_add_investment_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='special_offer',
            field=models.CharField(blank=True, max_length=50, verbose_name='Специальное предложение'),
        ),
        migrations.AddField(
            model_name='property',
            name='special_offer_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальное предложение'),
        ),
        migrations.AddField(
            model_name='property',
            name='special_offer_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальное предложение'),
        ),
        migrations.AddField(
            model_name='property',
            name='special_offer_th',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Специальное предложение'),
        ),
    ]
