# Generated by Django 5.0.6 on 2025-09-07 08:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_special_offer_property_special_offer_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_ru',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description_th',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
    ]
