# Generated by Django 5.0.6 on 2025-09-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_team_facebook_team_instagram_team_linkedin_and_more'),
        ('properties', '0016_add_tinymce_to_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_person',
            field=models.ForeignKey(blank=True, help_text='Сотрудник компании, ответственный за данный объект', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Ответственный агент (устаревшее поле)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.agent', verbose_name='Агент (legacy)'),
        ),
    ]
