# Generated by Django 5.0.6 on 2025-09-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_team_facebook_team_instagram_team_linkedin_and_more'),
        ('properties', '0017_add_contact_person_to_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contact_person',
            field=models.ForeignKey(blank=True, default=1, help_text='Сотрудник компании, ответственный за данный объект (по умолчанию: Bogdan)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team', verbose_name='Контактное лицо'),
        ),
    ]
