# Generated by Django 5.0.6 on 2025-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_set_default_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='name_plural',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название во множественном числе'),
        ),
    ]
