# Generated by Django 5.0.6 on 2025-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_propertytype_name_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='architectural_style_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Архитектурный стиль'),
        ),
        migrations.AddField(
            model_name='property',
            name='architectural_style_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Архитектурный стиль'),
        ),
        migrations.AddField(
            model_name='property',
            name='architectural_style_th',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Архитектурный стиль'),
        ),
        migrations.AddField(
            model_name='property',
            name='complex_name_en',
            field=models.CharField(blank=True, help_text='Название жилого комплекса или проекта', max_length=100, null=True, verbose_name='Название комплекса'),
        ),
        migrations.AddField(
            model_name='property',
            name='complex_name_ru',
            field=models.CharField(blank=True, help_text='Название жилого комплекса или проекта', max_length=100, null=True, verbose_name='Название комплекса'),
        ),
        migrations.AddField(
            model_name='property',
            name='complex_name_th',
            field=models.CharField(blank=True, help_text='Название жилого комплекса или проекта', max_length=100, null=True, verbose_name='Название комплекса'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_potential_en',
            field=models.TextField(blank=True, help_text='Описание инвестиционной привлекательности', null=True, verbose_name='Инвестиционный потенциал'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_potential_ru',
            field=models.TextField(blank=True, help_text='Описание инвестиционной привлекательности', null=True, verbose_name='Инвестиционный потенциал'),
        ),
        migrations.AddField(
            model_name='property',
            name='investment_potential_th',
            field=models.TextField(blank=True, help_text='Описание инвестиционной привлекательности', null=True, verbose_name='Инвестиционный потенциал'),
        ),
        migrations.AddField(
            model_name='property',
            name='material_type_en',
            field=models.CharField(blank=True, help_text='Основные строительные материалы', max_length=200, null=True, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='property',
            name='material_type_ru',
            field=models.CharField(blank=True, help_text='Основные строительные материалы', max_length=200, null=True, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='property',
            name='material_type_th',
            field=models.CharField(blank=True, help_text='Основные строительные материалы', max_length=200, null=True, verbose_name='Материалы'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_for_en',
            field=models.CharField(blank=True, help_text='Назначение использования (отпуск, постоянное проживание и т.д.)', max_length=200, null=True, verbose_name='Подходит для'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_for_ru',
            field=models.CharField(blank=True, help_text='Назначение использования (отпуск, постоянное проживание и т.д.)', max_length=200, null=True, verbose_name='Подходит для'),
        ),
        migrations.AddField(
            model_name='property',
            name='suitable_for_th',
            field=models.CharField(blank=True, help_text='Назначение использования (отпуск, постоянное проживание и т.д.)', max_length=200, null=True, verbose_name='Подходит для'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgency_note_en',
            field=models.CharField(blank=True, help_text='Дополнительная информация о срочной продаже', max_length=200, null=True, verbose_name='Примечание о срочности'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgency_note_ru',
            field=models.CharField(blank=True, help_text='Дополнительная информация о срочной продаже', max_length=200, null=True, verbose_name='Примечание о срочности'),
        ),
        migrations.AddField(
            model_name='property',
            name='urgency_note_th',
            field=models.CharField(blank=True, help_text='Дополнительная информация о срочной продаже', max_length=200, null=True, verbose_name='Примечание о срочности'),
        ),
    ]
