# Generated by Django 5.0.6 on 2025-11-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_property_architectural_style_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_priority',
            field=models.PositiveIntegerField(default=0, help_text='Чем выше значение, тем раньше объект отображается в блоках рекомендаций', verbose_name='Приоритет в рекомендуемых'),
        ),
    ]
