# Generated by Django 5.0.6 on 2026-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_featured_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='build_status',
            field=models.CharField(choices=[('completed', 'Готовый объект'), ('under_construction', 'Строящийся объект')], default='under_construction', help_text='Выберите "Готовый объект" или "Строящийся объект"', max_length=20, verbose_name='Стадия готовности'),
        ),
        migrations.AlterField(
            model_name='property',
            name='legacy_id',
            field=models.CharField(blank=True, help_text='Идентификатор из старой Joomla системы (например: VS82)', max_length=20, null=True, verbose_name='ID объекта'),
        ),
    ]
