# Generated by Django 5.0.6 on 2025-07-03 14:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 код (USD, EUR, RUB, THB)', max_length=3, unique=True, verbose_name='Код валюты')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('name_ru', models.CharField(blank=True, max_length=50, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=50, verbose_name='Название (EN)')),
                ('name_th', models.CharField(blank=True, max_length=50, verbose_name='Название (TH)')),
                ('symbol', models.CharField(help_text='Символ валюты ($, €, ₽, ฿)', max_length=10, verbose_name='Символ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_base', models.BooleanField(default=False, help_text='Базовая валюта для расчетов', verbose_name='Базовая валюта')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Знаков после запятой')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('th', 'ไทย')], max_length=2, unique=True, verbose_name='Язык')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.currency', verbose_name='Валюта по умолчанию')),
            ],
            options={
                'verbose_name': 'Предпочтение валюты',
                'verbose_name_plural': 'Предпочтения валют',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Курс')),
                ('date', models.DateField(verbose_name='Дата')),
                ('source', models.CharField(default='exchangerate-api.com', max_length=50, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='currency.currency', verbose_name='Базовая валюта')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_rates', to='currency.currency', verbose_name='Целевая валюта')),
            ],
            options={
                'verbose_name': 'Курс обмена',
                'verbose_name_plural': 'Курсы обмена',
                'ordering': ['-date', 'base_currency', 'target_currency'],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
    ]
