# Generated by Django 5.0.6 on 2025-06-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('property_detail', 'Карточка недвижимости'), ('property_list_type', 'Список по типу недвижимости'), ('property_list_location', 'Список по локации')], max_length=50, verbose_name='Тип шаблона')),
                ('property_type', models.CharField(blank=True, help_text='Оставьте пустым для применения ко всем типам', max_length=50, verbose_name='Тип недвижимости')),
                ('deal_type', models.CharField(blank=True, choices=[('sale', 'Продажа'), ('rent', 'Аренда'), ('both', 'Продажа/Аренда')], help_text='Оставьте пустым для применения ко всем типам сделок', max_length=20, verbose_name='Тип сделки')),
                ('title_template_ru', models.CharField(help_text='Используйте переменные: {title}, {type}, {location}, {district}, {price}, {area}', max_length=200, verbose_name='Шаблон заголовка (RU)')),
                ('description_template_ru', models.TextField(help_text='Используйте переменные: {title}, {type}, {location}, {district}, {price}, {area}, {rooms}', max_length=300, verbose_name='Шаблон описания (RU)')),
                ('keywords_template_ru', models.TextField(help_text='Используйте переменные через запятую', verbose_name='Шаблон ключевых слов (RU)')),
                ('title_template_en', models.CharField(blank=True, max_length=200, verbose_name='Шаблон заголовка (EN)')),
                ('description_template_en', models.TextField(blank=True, max_length=300, verbose_name='Шаблон описания (EN)')),
                ('keywords_template_en', models.TextField(blank=True, verbose_name='Шаблон ключевых слов (EN)')),
                ('title_template_th', models.CharField(blank=True, max_length=200, verbose_name='Шаблон заголовка (TH)')),
                ('description_template_th', models.TextField(blank=True, max_length=300, verbose_name='Шаблон описания (TH)')),
                ('keywords_template_th', models.TextField(blank=True, verbose_name='Шаблон ключевых слов (TH)')),
                ('priority', models.IntegerField(default=100, help_text='Чем меньше число, тем выше приоритет', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'SEO шаблон',
                'verbose_name_plural': 'SEO шаблоны',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='seopage',
            options={'verbose_name': 'SEO страница', 'verbose_name_plural': 'SEO страницы'},
        ),
        migrations.AlterField(
            model_name='seopage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='page_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя страницы'),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
