# Generated by Django 5.0.6 on 2025-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seotemplate_deal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Рекомендуемое разрешение: 1920x1080 пикселей', upload_to='promotional_banners/', verbose_name='Фоновое изображение')),
                ('discount_text', models.CharField(blank=True, help_text='Например: "Скидка 20%" или "Ограниченное предложение"', max_length=100, verbose_name='Текст скидки/предложения')),
                ('valid_until', models.DateField(blank=True, help_text='Дата окончания действия предложения', null=True, verbose_name='Действительно до')),
                ('button_text', models.CharField(blank=True, help_text='Например: "Узнать подробнее" или "Связаться с нами"', max_length=50, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, help_text='URL или имя Django URL pattern', max_length=200, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли баннер на сайте', verbose_name='Активно')),
                ('priority', models.IntegerField(default=100, help_text='Чем меньше число, тем выше приоритет. Показывается баннер с наивысшим приоритетом', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
