# Generated by Django 5.0.6 on 2025-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_promotionalbanner_button_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('role', models.CharField(choices=[('sales_director', 'Sales Director'), ('senior_manager', 'Senior Manager for International Client Relations'), ('manager', 'Manager for International Client Relations'), ('chief_art_officer', 'Chief Art Officer (CAO)'), ('chief_marketing_officer', 'Chief Marketing Officer (CMO)'), ('chief_financial_officer', 'Chief Financial Officer (CFO)'), ('office_manager', 'Office Manager'), ('agent', 'Агент по недвижимости'), ('specialist', 'Специалист'), ('other', 'Другое')], default='specialist', max_length=50, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('whatsapp', models.CharField(blank=True, help_text='Номер телефона для WhatsApp', max_length=20, verbose_name='WhatsApp')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемое разрешение: 300x300 пикселей', upload_to='team/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, help_text='Краткая информация о сотруднике', verbose_name='Биография')),
                ('specialization', models.TextField(blank=True, help_text='Основные направления работы', verbose_name='Специализация')),
                ('languages', models.CharField(blank=True, help_text='Перечислите языки через запятую', max_length=200, verbose_name='Языки')),
                ('is_active', models.BooleanField(default=True, help_text='Показывать ли сотрудника на сайте', verbose_name='Активный')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Отображать в блоке "Наша команда" на главной странице', verbose_name='Показывать на главной')),
                ('display_order', models.IntegerField(default=100, help_text='Порядок отображения в списке (меньше = выше)', verbose_name='Порядок отображения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['display_order', 'last_name', 'first_name'],
            },
        ),
    ]
