# Generated by Django 5.0.6 on 2025-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebook',
            field=models.URLField(blank=True, help_text='Ссылка на профиль в Facebook', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True, help_text='Ссылка на профиль в Instagram', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Ссылка на профиль в LinkedIn', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='team',
            name='telegram',
            field=models.CharField(blank=True, help_text='Username в Telegram (без @)', max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='team',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Ссылка на профиль в TikTok', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='team',
            name='twitter',
            field=models.URLField(blank=True, help_text='Ссылка на профиль в Twitter', verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='team',
            name='youtube',
            field=models.URLField(blank=True, help_text='Ссылка на канал YouTube', verbose_name='YouTube'),
        ),
    ]
