# Generated by Django 5.0.6 on 2025-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_promotionalbanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Используется в шаблонах, например: properties_sale, properties_type_condo', max_length=150, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(blank=True, help_text='Опциональный заголовок блока, можно оставить пустым.', max_length=200, verbose_name='Заголовок')),
                ('content_ru', models.TextField(blank=True, verbose_name='Контент (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Контент (EN)')),
                ('content_th', models.TextField(blank=True, verbose_name='Контент (TH)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'SEO блок',
                'verbose_name_plural': 'SEO блоки',
                'ordering': ['slug'],
            },
        ),
    ]
