# Generated by Django 5.0.6 on 2026-01-20 18:48

from django.db import migrations, models


def populate_team_translations(apps, schema_editor):
    Team = apps.get_model('core', 'Team')

    ru_mapping = {
        ('Bogdan', 'Dyachuk'): {
            'first_name_ru': 'Богдан',
            'last_name_ru': 'Дьячук',
            'position_ru': 'Директор по продажам',
        },
        ('Kirill', 'Dediugin'): {
            'first_name_ru': 'Кирилл',
            'last_name_ru': 'Дедюгин',
            'position_ru': 'Руководитель отдела продаж',
        },
        ('Vitalii', 'Savchuk'): {
            'first_name_ru': 'Виталий',
            'last_name_ru': 'Савчук',
            'position_ru': 'Менеджер по продажам',
        },
        ('Ilya', 'Ordovskii-Tanaevskii'): {
            'first_name_ru': 'Илья',
            'last_name_ru': 'Ордовский-Танаевский',
            'position_ru': 'Креативный директор (CAO)',
        },
        ('Tatiana', 'Korostyleva'): {
            'first_name_ru': 'Татьяна',
            'last_name_ru': 'Коростылева',
            'position_ru': 'Директор по маркетингу (CMO)',
        },
        ('Aleksei', 'Kljujev'): {
            'first_name_ru': 'Алексей',
            'last_name_ru': 'Клюев',
            'position_ru': 'Финансовый директор (CFO)',
        },
        ('Withanyu', 'Satchaphan'): {
            'first_name_ru': 'Витанью',
            'last_name_ru': 'Сатчапхан',
            'position_ru': 'Офис-менеджер',
        },
    }

    for member in Team.objects.all():
        key = (member.first_name, member.last_name)

        member.first_name_en = member.first_name
        member.last_name_en = member.last_name
        member.position_en = member.position

        ru_values = ru_mapping.get(key)
        if ru_values:
            member.first_name_ru = ru_values['first_name_ru']
            member.last_name_ru = ru_values['last_name_ru']
            member.position_ru = ru_values['position_ru']
        else:
            member.first_name_ru = member.first_name_ru or member.first_name
            member.last_name_ru = member.last_name_ru or member.last_name
            member.position_ru = member.position_ru or member.position

        member.save(update_fields=[
            'first_name_ru', 'first_name_en',
            'last_name_ru', 'last_name_en',
            'position_ru', 'position_en',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_seocontentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='first_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='first_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='first_name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='team',
            name='last_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='team',
            name='last_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='team',
            name='last_name_th',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_th',
            field=models.CharField(max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.RunPython(populate_team_translations, migrations.RunPython.noop),
    ]
