# Generated by Django 5.0.6 on 2026-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_manualipban'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='asn',
            field=models.CharField(blank=True, max_length=32, verbose_name='ASN'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='asn_organization',
            field=models.CharField(blank=True, max_length=255, verbose_name='ASN организация'),
        ),
    ]
