# Generated by Django 5.0.6 on 2026-06-26 11:51

from django.db import migrations, models


def populate_team_profile_ru_fields(apps, schema_editor):
    Team = apps.get_model('core', 'Team')

    for member in Team.objects.all():
        update_fields = []

        for field_name in ('bio', 'specialization', 'languages'):
            source_value = getattr(member, field_name, '') or ''
            target_field = f'{field_name}_ru'
            if source_value and not getattr(member, target_field, ''):
                setattr(member, target_field, source_value)
                update_fields.append(target_field)

        if update_fields:
            member.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_update_bogdan_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio_en',
            field=models.TextField(blank=True, help_text='Краткая информация о сотруднике', null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='team',
            name='bio_ru',
            field=models.TextField(blank=True, help_text='Краткая информация о сотруднике', null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='team',
            name='bio_th',
            field=models.TextField(blank=True, help_text='Краткая информация о сотруднике', null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='team',
            name='languages_en',
            field=models.CharField(blank=True, help_text='Перечислите языки через запятую', max_length=200, null=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='team',
            name='languages_ru',
            field=models.CharField(blank=True, help_text='Перечислите языки через запятую', max_length=200, null=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='team',
            name='languages_th',
            field=models.CharField(blank=True, help_text='Перечислите языки через запятую', max_length=200, null=True, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='team',
            name='specialization_en',
            field=models.TextField(blank=True, help_text='Основные направления работы', null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='team',
            name='specialization_ru',
            field=models.TextField(blank=True, help_text='Основные направления работы', null=True, verbose_name='Специализация'),
        ),
        migrations.AddField(
            model_name='team',
            name='specialization_th',
            field=models.TextField(blank=True, help_text='Основные направления работы', null=True, verbose_name='Специализация'),
        ),
        migrations.RunPython(populate_team_profile_ru_fields, migrations.RunPython.noop),
    ]
