# Generated by Django 5.0.6 on 2026-06-26 12:07

from django.db import migrations, models
from django.utils.text import slugify


def populate_team_slugs(apps, schema_editor):
    Team = apps.get_model('core', 'Team')

    for member in Team.objects.all().order_by('id'):
        if member.slug:
            continue

        candidates = [
            f"{member.first_name_en or ''} {member.last_name_en or ''}",
            f"{member.first_name or ''} {member.last_name or ''}",
            f"{member.first_name_ru or ''} {member.last_name_ru or ''}",
        ]

        base_slug = ''
        for candidate in candidates:
            base_slug = slugify(candidate)
            if base_slug:
                break

        if not base_slug:
            base_slug = f'team-member-{member.pk}'

        slug = base_slug[:150].strip('-') or f'team-member-{member.pk}'
        counter = 2

        while Team.objects.filter(slug=slug).exclude(pk=member.pk).exists():
            suffix = f'-{counter}'
            slug = f'{base_slug[:150 - len(suffix)].strip("-")}{suffix}'
            counter += 1

        member.slug = slug
        member.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_team_bio_en_team_bio_ru_team_bio_th_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='market_since_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Например 2018. Используется для отображения опыта на публичной странице', null=True, verbose_name='Год начала работы на рынке'),
        ),
        migrations.AddField(
            model_name='team',
            name='prea_role',
            field=models.CharField(blank=True, help_text='Фактическая роль или участие в профессиональной ассоциации, если применимо', max_length=255, verbose_name='Роль в Phuket Property Association'),
        ),
        migrations.AddField(
            model_name='team',
            name='prea_role_en',
            field=models.CharField(blank=True, help_text='Фактическая роль или участие в профессиональной ассоциации, если применимо', max_length=255, null=True, verbose_name='Роль в Phuket Property Association'),
        ),
        migrations.AddField(
            model_name='team',
            name='prea_role_ru',
            field=models.CharField(blank=True, help_text='Фактическая роль или участие в профессиональной ассоциации, если применимо', max_length=255, null=True, verbose_name='Роль в Phuket Property Association'),
        ),
        migrations.AddField(
            model_name='team',
            name='prea_role_th',
            field=models.CharField(blank=True, help_text='Фактическая роль или участие в профессиональной ассоциации, если применимо', max_length=255, null=True, verbose_name='Роль в Phuket Property Association'),
        ),
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, help_text='Стабильный URL сотрудника, например bogdan-dyachuk', max_length=160, null=True, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.RunPython(populate_team_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, help_text='Стабильный URL сотрудника, например bogdan-dyachuk', max_length=160, unique=True, verbose_name='URL-адрес'),
        ),
    ]
