# Generated by Django 5.0.6 on 2025-07-07 20:06

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('name_th', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_th', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('color', models.CharField(default='#007bff', help_text='Цвет категории в формате HEX (#ffffff)', max_length=7, verbose_name='Цвет')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_th', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='SEO описание')),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_th', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_ru', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_en', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_th', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Категория блога',
                'verbose_name_plural': 'Категории блога',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_th', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('excerpt', models.TextField(help_text='Краткое описание статьи для превью', max_length=500, verbose_name='Краткое описание')),
                ('excerpt_ru', models.TextField(help_text='Краткое описание статьи для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('excerpt_en', models.TextField(help_text='Краткое описание статьи для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('excerpt_th', models.TextField(help_text='Краткое описание статьи для превью', max_length=500, null=True, verbose_name='Краткое описание')),
                ('content', tinymce.models.HTMLField(verbose_name='Содержание статьи')),
                ('content_ru', tinymce.models.HTMLField(null=True, verbose_name='Содержание статьи')),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name='Содержание статьи')),
                ('content_th', tinymce.models.HTMLField(null=True, verbose_name='Содержание статьи')),
                ('featured_image', models.ImageField(blank=True, help_text='Главное изображение статьи', upload_to='blog/featured/', verbose_name='Главное изображение')),
                ('featured_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст изображения')),
                ('featured_image_alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст изображения')),
                ('featured_image_alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст изображения')),
                ('featured_image_alt_th', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст изображения')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('meta_title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_title_th', models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=300, verbose_name='SEO описание')),
                ('meta_description_ru', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_en', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_description_th', models.TextField(blank=True, max_length=300, null=True, verbose_name='SEO описание')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_ru', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_en', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('meta_keywords_th', models.TextField(blank=True, null=True, verbose_name='SEO ключевые слова')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'В архиве')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_featured', models.BooleanField(default=False, help_text='Отображать в блоке рекомендуемых статей', verbose_name='Рекомендуемая')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Разрешить комментарии')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья блога',
                'verbose_name_plural': 'Статьи блога',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='blog.blogpost', verbose_name='Статьи')),
            ],
            options={
                'verbose_name': 'Тег блога',
                'verbose_name_plural': 'Теги блога',
                'ordering': ['name'],
            },
        ),
    ]
