# Generated by Django 5.0.6 on 2025-07-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_type',
            field=models.CharField(choices=[('article', 'Статья'), ('news', 'Новость'), ('case', 'Кейс'), ('review', 'Обзор'), ('place_activity', 'Места и активности'), ('upcoming_event', 'Будущее мероприятие'), ('past_event', 'Завершенное мероприятие')], default='article', help_text='Тип контента влияет на отображение и фильтрацию', max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Для мероприятий - дата проведения', null=True, verbose_name='Дата события'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='event_location',
            field=models.CharField(blank=True, help_text='Для мероприятий - место проведения', max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='event_price',
            field=models.CharField(blank=True, help_text='Для мероприятий - стоимость участия', max_length=100, verbose_name='Стоимость участия'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_id',
            field=models.CharField(blank=True, help_text='ID статьи на исходном сайте', max_length=50, verbose_name='Оригинальный ID'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_url',
            field=models.URLField(blank=True, help_text='URL статьи на исходном сайте', verbose_name='Оригинальный URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='project_url',
            field=models.URLField(blank=True, help_text='Для кейсов - ссылка на проект', verbose_name='Ссылка на проект'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='rating',
            field=models.PositiveIntegerField(blank=True, help_text='Для обзоров - рейтинг от 1 до 5', null=True, verbose_name='Рейтинг'),
        ),
    ]
