# Generated by Django 5.0.6 on 2025-07-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content_type_blogpost_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_type',
        ),
    ]
