# Generated by Django 5.0.6 on 2025-09-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_content_type_field'),
        ('core', '0012_team_facebook_team_instagram_team_linkedin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='team_author',
            field=models.ForeignKey(blank=True, help_text='Сотрудник компании - автор статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.team', verbose_name='Автор (сотрудник)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(help_text='Пользователь системы - автор статьи (устаревшее поле)', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор (legacy)'),
        ),
    ]
