# Generated by Django 5.0.6 on 2025-09-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_team_author_to_blogpost'),
        ('core', '0012_team_facebook_team_instagram_team_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='team_author',
            field=models.ForeignKey(blank=True, default=5, help_text='Сотрудник компании - автор статьи (по умолчанию: Tatiana)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.team', verbose_name='Автор (сотрудник)'),
        ),
    ]
