# Generated by Django 5.0.6 on 2025-10-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_set_default_team_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_en',
            field=models.ImageField(blank=True, help_text='Локализованное изображение статьи для английской версии', upload_to='blog/featured/', verbose_name='Главное изображение (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_th',
            field=models.ImageField(blank=True, help_text='Локализованное изображение статьи для тайской версии', upload_to='blog/featured/', verbose_name='Главное изображение (TH)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_url_en',
            field=models.URLField(blank=True, help_text='URL английской версии статьи на исходном сайте', verbose_name='Оригинальный URL (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_url_th',
            field=models.URLField(blank=True, help_text='URL тайской версии статьи на исходном сайте', verbose_name='Оригинальный URL (TH)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Главное изображение статьи для русской версии', upload_to='blog/featured/', verbose_name='Главное изображение (RU)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='original_url',
            field=models.URLField(blank=True, help_text='URL русской версии статьи на исходном сайте', verbose_name='Оригинальный URL (RU)'),
        ),
    ]
