# Generated by Django 5.0.6 on 2026-05-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_featured_image_en_and_more'),
        ('properties', '0023_propertyimage_alt_generation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostPropertyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше объект в блоке статьи', verbose_name='Порядок')),
                ('editor_note', models.CharField(blank=True, help_text='Короткое пояснение, почему объект связан со статьей. Показывается на странице статьи.', max_length=180, verbose_name='Комментарий редактора')),
                ('editor_note_en', models.CharField(blank=True, help_text='Короткое пояснение, почему объект связан со статьей. Показывается на странице статьи.', max_length=180, null=True, verbose_name='Комментарий редактора')),
                ('editor_note_ru', models.CharField(blank=True, help_text='Короткое пояснение, почему объект связан со статьей. Показывается на странице статьи.', max_length=180, null=True, verbose_name='Комментарий редактора')),
                ('editor_note_th', models.CharField(blank=True, help_text='Короткое пояснение, почему объект связан со статьей. Показывается на странице статьи.', max_length=180, null=True, verbose_name='Комментарий редактора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_links', to='blog.blogpost', verbose_name='Статья')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_links', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Объект в статье блога',
                'verbose_name_plural': 'Объекты в статье блога',
                'ordering': ['order', 'id'],
                'unique_together': {('post', 'property')},
            },
        ),
    ]
