# Generated by AI assistant on 2026-06-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpostpropertylink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTranslationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'В работе'), ('succeeded', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('target_languages', models.JSONField(blank=True, default=list, verbose_name='Языки перевода')),
                ('force_retranslate', models.BooleanField(default=False, verbose_name='Перезаписать существующие переводы')),
                ('provider', models.CharField(blank=True, default='yandex', max_length=50, verbose_name='Провайдер')),
                ('total_fields', models.PositiveIntegerField(default=0, verbose_name='Всего полей')),
                ('completed_fields', models.PositiveIntegerField(default=0, verbose_name='Переведено полей')),
                ('skipped_fields', models.PositiveIntegerField(default=0, verbose_name='Пропущено полей')),
                ('failed_fields', models.PositiveIntegerField(default=0, verbose_name='Ошибок полей')),
                ('current_language', models.CharField(blank=True, max_length=10, verbose_name='Текущий язык')),
                ('current_field', models.CharField(blank=True, max_length=80, verbose_name='Текущее поле')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('log', models.TextField(blank=True, verbose_name='Журнал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_jobs', to='blog.blogpost', verbose_name='Статья')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_translation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Поставил в очередь')),
            ],
            options={
                'verbose_name': 'Задание перевода статьи',
                'verbose_name_plural': 'Задания перевода статей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogtranslationjob',
            index=models.Index(fields=['status', 'created_at'], name='blog_blogtr_status_9e1d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='blogtranslationjob',
            index=models.Index(fields=['post', '-created_at'], name='blog_blogtr_post_id_636c23_idx'),
        ),
    ]
