# Generated by Django 5.0.6 on 2026-07-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_update_transliterated_blog_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=300, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='Вопрос')),
                ('question_th', models.CharField(max_length=300, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_th', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=100, help_text='Чем меньше число, тем выше вопрос в блоке FAQ', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на странице')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='blog.blogpost', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Вопрос и ответ статьи',
                'verbose_name_plural': 'FAQ статьи',
                'ordering': ['order', 'id'],
            },
        ),
    ]
