# Generated by Django 5.0.6 on 2025-08-01 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название маппинга')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('field_mapping', models.JSONField(default=dict, verbose_name='Маппинг полей')),
                ('header_row', models.PositiveIntegerField(default=1, help_text='Номер строки с заголовками (1-based)', verbose_name='Строка заголовков')),
                ('data_start_row', models.PositiveIntegerField(default=2, help_text='Номер первой строки с данными (1-based)', verbose_name='Начало данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Маппинг импорта',
                'verbose_name_plural': 'Маппинги импорта',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Файл')),
                ('import_type', models.CharField(choices=[('property_update', 'Обновление недвижимости'), ('property_create', 'Создание недвижимости'), ('price_update', 'Обновление цен')], max_length=20, verbose_name='Тип импорта')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Обработано строк')),
                ('successful_rows', models.PositiveIntegerField(default=0, verbose_name='Успешно обработано')),
                ('failed_rows', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('parsed_data', models.JSONField(blank=True, null=True, verbose_name='Распарсенные данные')),
                ('validation_errors', models.JSONField(blank=True, null=True, verbose_name='Ошибки валидации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_import.propertyimportmapping', verbose_name='Маппинг полей')),
            ],
            options={
                'verbose_name': 'Файл импорта',
                'verbose_name_plural': 'Файлы импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех')], max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('row_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_import.importfile')),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['created_at'],
            },
        ),
    ]
