# Generated by Django 5.0.6 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте обложку района (используется на странице детального описания и списке районов).', null=True, upload_to='locations/districts/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Опциональная фотография локации для детальной страницы.', null=True, upload_to='locations/locations/', verbose_name='Изображение'),
        ),
    ]
