# Generated by Django 5.0.6 on 2025-07-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PropertyFavorite',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
