# Generated by Django 5.0.6 on 2025-10-01 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_set_default_contact_person'),
        ('users', '0002_remove_userprofile_user_delete_propertyfavorite_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Страница подписки')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отписки')),
            ],
            options={
                'verbose_name': 'Подписка на новости',
                'verbose_name_plural': 'Подписки на новости',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='propertyinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос по объекту', 'verbose_name_plural': 'Запросы по объектам'},
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='consultation_topic',
            field=models.CharField(blank=True, choices=[('price', 'Уточнение цены'), ('investment', 'Инвестиционный потенциал'), ('documents', 'Документы и оформление'), ('location', 'О районе и инфраструктуре'), ('other', 'Другое')], max_length=20, verbose_name='Тема консультации'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('viewing', 'Запись на просмотр'), ('consultation', 'Консультация'), ('general', 'Общий вопрос')], default='general', max_length=20, verbose_name='Тип запроса'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='preferred_contact',
            field=models.CharField(blank=True, choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20, verbose_name='Предпочтительный способ связи'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='preferred_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Желаемая дата'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property', verbose_name='Объект'),
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('property', 'Вопрос о недвижимости'), ('services', 'Услуги компании'), ('partnership', 'Сотрудничество'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('amo_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в AmoCRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Обращение с контактной формы',
                'verbose_name_plural': 'Обращения с контактной формы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('privacy_consent', models.BooleanField(default=True, verbose_name='Согласие с политикой конфиденциальности')),
                ('amo_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в AmoCRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Вопрос из FAQ',
                'verbose_name_plural': 'Вопросы из FAQ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeVisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('preferred_date', models.DateField(verbose_name='Желаемая дата')),
                ('message', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('privacy_consent', models.BooleanField(default=True, verbose_name='Согласие с политикой конфиденциальности')),
                ('amo_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в AmoCRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('visit_confirmed', models.BooleanField(default=False, verbose_name='Встреча подтверждена')),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Подтвержденная дата и время')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Запись на встречу в офисе',
                'verbose_name_plural': 'Записи на встречу в офисе',
                'ordering': ['-preferred_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Страница отправки')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('amo_lead_id', models.IntegerField(blank=True, null=True, verbose_name='ID лида в AmoCRM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
            ],
            options={
                'verbose_name': 'Быстрая консультация',
                'verbose_name_plural': 'Быстрые консультации',
                'ordering': ['-created_at'],
            },
        ),
    ]
