# Generated by Django 5.0.6 on 2025-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newslettersubscription_alter_propertyinquiry_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('viewing', 'Запись на просмотр'), ('consultation', 'Консультация'), ('callback', 'Заказ обратного звонка'), ('general', 'Общий вопрос')], default='general', max_length=20, verbose_name='Тип запроса'),
        ),
    ]
