# Generated by Django 5.0.6 on 2025-10-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_callback_inquiry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('viewing', 'Запись на просмотр'), ('consultation', 'Консультация'), ('callback', 'Заказ обратного звонка'), ('custom_selection', 'Индивидуальный подбор недвижимости'), ('general', 'Общий вопрос')], default='general', max_length=20, verbose_name='Тип запроса'),
        ),
    ]
