from copy import deepcopy


SERVICE_LANDING_CONTENT = {
    'buying-property': {
        'ru': {
            'badge': 'Покупка недвижимости',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Покупатель рискует переплатить, выбрать неподходящий объект или зайти в сделку без проверки документов и реальной рыночной картины.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Покупателям, которые хотят безопасно купить объект на Пхукете для жизни, отдыха или инвестиций.',
                'Клиентам, которым нужен отбор только проверенных объектов без хаотичных просмотров.',
                'Инвесторам, которым важно сравнить доходность, ликвидность и юридическую чистоту проекта.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Бриф и стратегия', 'text': 'Фиксируем бюджет, цель покупки, желаемую локацию, формат недвижимости и сроки выхода в сделку.'},
                {'title': 'Подбор и short list', 'text': 'Формируем shortlist объектов, сравниваем цены, локации, застройщиков и переговорные возможности.'},
                {'title': 'Проверка и переговоры', 'text': 'Проверяем документы, условия бронирования, схему оплаты и аргументированно ведём переговоры.'},
                {'title': 'Сделка и пост-сделка', 'text': 'Сопровождаем договоры, платежи, регистрацию и передаём объект клиенту с понятным чек-листом.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Паспорт покупателя и контактные данные.',
                'Данные для договора и регистрации собственности.',
                'Подтверждение источника средств и банковские реквизиты для оплаты.',
                'По проектам off-plan: график платежей, reservation agreement, draft SPA.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Покупка объекта по завышенной цене относительно текущего рынка.',
                'Подписание договора без проверки ограничений, сроков и скрытых обязательств.',
                'Выбор проекта без оценки ликвидности, управляющей модели и вторичного спроса.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Первичный shortlist обычно готовим в течение 1–3 дней. Полный цикл до бронирования и подписания зависит от типа объекта и скорости согласования условий.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Для покупателя наша комиссия обычно уже включена в модель сделки с продавцом или девелопером. Отдельные расходы возникают только по юридическому сопровождению, due diligence и регистрации, если они требуются.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Можно ли купить объект дистанционно?', 'answer': 'Да. Мы выстраиваем процесс так, чтобы клиент мог пройти подбор, проверку и подписание документов удалённо.'},
                {'question': 'Вы работаете только с новостройками?', 'answer': 'Нет. Мы подбираем как первичный рынок, так и resale, если объект соответствует задаче клиента.'},
                {'question': 'Помогаете ли вы после покупки?', 'answer': 'Да. При необходимости подключаем управление объектом, перепродажу, аренду и дополнительные сервисы.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Покупка для жизни', 'text': 'Подобрали клиенту готовую квартиру у моря, снизили цену на переговорах и провели сделку без очного присутствия покупателя.'},
                {'title': 'Инвестиционный вход', 'text': 'Сравнили несколько проектов off-plan, просчитали доходность и помогли выбрать лот с лучшей ликвидностью на выходе.'},
            ],
            'cta_title': 'Обсудим вашу покупку',
            'cta_text': 'Расскажите, какой объект вы ищете, а мы подготовим shortlist, проверим риски и предложим оптимальный сценарий сделки.',
            'cta_button': 'Получить консультацию',
        },
        'en': {
            'badge': 'Property purchase',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Buyers can overpay, choose the wrong asset, or enter a deal without document checks and a realistic view of the market.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'Buyers who want to purchase Phuket property safely for living, lifestyle, or investment.',
                'Clients who need a curated shortlist instead of chaotic viewings.',
                'Investors who want to compare yield, liquidity, and legal quality before committing.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Brief and strategy', 'text': 'We define budget, acquisition goals, preferred location, property format, and target timeline.'},
                {'title': 'Selection and shortlist', 'text': 'We prepare a shortlist and compare pricing, locations, developers, and negotiation potential.'},
                {'title': 'Checks and negotiation', 'text': 'We review documents, reservation terms, payment schedule, and negotiate with clear market arguments.'},
                {'title': 'Closing and post-closing', 'text': 'We support contracts, payments, registration, and handover with a clear action checklist.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Buyer passport and contact details.',
                'Contract and ownership registration details.',
                'Proof of funds and payment banking details.',
                'For off-plan projects: payment schedule, reservation agreement, and SPA draft.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'Buying above the real market benchmark.',
                'Signing documents without checking obligations, limitations, and deadlines.',
                'Selecting a project without validating liquidity, management quality, and resale demand.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'A first shortlist is usually ready within 1–3 days. The full route to reservation and signing depends on the asset type and speed of approvals.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'For buyers, our fee is usually already built into the deal structure with the seller or developer. Separate costs may arise only for legal support, due diligence, and registration when required.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Can I buy remotely?', 'answer': 'Yes. We structure the process so selection, checks, and document signing can be handled remotely.'},
                {'question': 'Do you work only with new developments?', 'answer': 'No. We source both primary and resale stock when it matches the client brief.'},
                {'question': 'Do you help after the purchase?', 'answer': 'Yes. We can support rental setup, resale strategy, management, and related services.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Lifestyle purchase', 'text': 'We sourced a ready condo near the sea, negotiated a price reduction, and closed the deal without the buyer being physically present.'},
                {'title': 'Investment entry', 'text': 'We compared several off-plan projects, modelled the returns, and helped the client select the most liquid exit scenario.'},
            ],
            'cta_title': 'Let’s discuss your purchase',
            'cta_text': 'Tell us what you want to buy, and we will prepare a shortlist, check the risks, and map out the right acquisition path.',
            'cta_button': 'Get a consultation',
        },
        'th': {
            'badge': 'การซื้ออสังหาริมทรัพย์',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'ผู้ซื้ออาจจ่ายแพงเกินจริง เลือกทรัพย์ไม่ตรงเป้าหมาย หรือเข้าสู่ดีลโดยไม่ได้ตรวจเอกสารและสภาพตลาดอย่างรอบคอบ.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'ผู้ซื้อที่ต้องการซื้ออสังหาริมทรัพย์ในภูเก็ตอย่างปลอดภัยเพื่ออยู่อาศัย พักผ่อน หรือการลงทุน.',
                'ลูกค้าที่ต้องการ shortlist ที่คัดกรองแล้วแทนการดูทรัพย์แบบกระจัดกระจาย.',
                'นักลงทุนที่ต้องการเทียบผลตอบแทน สภาพคล่อง และความพร้อมทางกฎหมายก่อนตัดสินใจ.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'บรีฟและวางกลยุทธ์', 'text': 'กำหนดงบประมาณ เป้าหมายการซื้อ ทำเล ประเภทอสังหาริมทรัพย์ และกรอบเวลา.'},
                {'title': 'คัดเลือกและทำ shortlist', 'text': 'คัดทรัพย์และเปรียบเทียบราคา ทำเล ผู้พัฒนา และศักยภาพในการต่อรอง.'},
                {'title': 'ตรวจสอบและเจรจา', 'text': 'ตรวจเอกสาร เงื่อนไขการจอง แผนการชำระเงิน และเจรจาด้วยข้อมูลตลาดที่ชัดเจน.'},
                {'title': 'ปิดดีลและหลังการซื้อ', 'text': 'ดูแลสัญญา การชำระเงิน การจดทะเบียน และการส่งมอบพร้อม checklist ที่ชัดเจน.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'หนังสือเดินทางและข้อมูลติดต่อของผู้ซื้อ.',
                'ข้อมูลสำหรับสัญญาและการจดทะเบียนกรรมสิทธิ์.',
                'หลักฐานที่มาของเงินและข้อมูลบัญชีสำหรับการชำระเงิน.',
                'สำหรับโครงการ off-plan: แผนการชำระเงิน reservation agreement และร่าง SPA.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ซื้อทรัพย์ในราคาสูงกว่าระดับตลาดจริง.',
                'ลงนามเอกสารโดยไม่ตรวจข้อผูกพัน เงื่อนไข และกำหนดเวลา.',
                'เลือกโครงการโดยไม่ประเมินสภาพคล่อง การบริหาร และดีมานด์ต่อในอนาคต.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'โดยปกติ shortlist ชุดแรกจะพร้อมภายใน 1–3 วัน ส่วนระยะเวลาจนถึงการจองและลงนามขึ้นอยู่กับประเภททรัพย์และความเร็วในการอนุมัติ.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'โดยทั่วไปค่าคอมมิชชั่นของเราสำหรับผู้ซื้อรวมอยู่ในโครงสร้างดีลกับผู้ขายหรือผู้พัฒนาอยู่แล้ว ค่าใช้จ่ายเพิ่มเติมจะเกิดขึ้นเฉพาะงานกฎหมาย due diligence และการจดทะเบียนหากจำเป็น.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'ซื้อจากต่างประเทศได้ไหม?', 'answer': 'ได้ เราจัดกระบวนการให้ลูกค้าสามารถคัดเลือก ตรวจสอบ และลงนามเอกสารจากระยะไกลได้.'},
                {'question': 'ทำเฉพาะโครงการใหม่หรือไม่?', 'answer': 'ไม่ เราดูทั้งตลาดใหม่และ resale หากตรงกับ brief ของลูกค้า.'},
                {'question': 'หลังซื้อแล้วช่วยต่อไหม?', 'answer': 'ช่วยได้ ทั้งการปล่อยเช่า การขายต่อ การบริหาร และบริการต่อเนื่องอื่น ๆ.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'ซื้อเพื่ออยู่อาศัย', 'text': 'คัดคอนโดพร้อมอยู่ใกล้ทะเล ต่อรองราคา และปิดดีลโดยที่ผู้ซื้อไม่ต้องเดินทางมาเอง.'},
                {'title': 'ซื้อเพื่อการลงทุน', 'text': 'เปรียบเทียบหลายโครงการ off-plan คำนวณผลตอบแทน และช่วยเลือกลอตที่มีสภาพคล่องดีที่สุด.'},
            ],
            'cta_title': 'เริ่มต้นการซื้อของคุณ',
            'cta_text': 'บอกเราว่าคุณกำลังมองหาอะไร แล้วเราจะช่วยคัด shortlist ตรวจความเสี่ยง และวางเส้นทางซื้อที่เหมาะสม.',
            'cta_button': 'ขอคำปรึกษา',
        },
    },
    'selling-property': {
        'ru': {
            'badge': 'Продажа недвижимости',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Собственник часто выходит на рынок без стратегии цены, без внятной упаковки объекта и без понятной схемы переговоров с покупателем.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Собственникам, которые хотят продать объект без затянутого экспонирования.',
                'Инвесторам, которым важно выйти из актива по рыночной цене и в разумный срок.',
                'Продавцам, которым нужен один координирующий партнёр по маркетингу, показам и переговорам.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Аудит объекта', 'text': 'Оцениваем позиционирование, конкурентное окружение, ликвидность и оптимальный ценовой коридор.'},
                {'title': 'Упаковка и маркетинг', 'text': 'Готовим визуалы, тексты, презентацию и запускаем продвижение по релевантным каналам.'},
                {'title': 'Лиды и показы', 'text': 'Фильтруем входящие обращения, организуем показы и фиксируем обратную связь рынка.'},
                {'title': 'Переговоры и закрытие', 'text': 'Сопровождаем оффер, резерв, договорённости по расчётам и финальное оформление.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Документ, подтверждающий право собственности.',
                'Паспорт собственника или данные компании-владельца.',
                'Планировки, технические параметры и история владения.',
                'Информация об обременениях, платежах и обслуживающей компании.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Завышенная цена, которая блокирует спрос и удлиняет экспозицию.',
                'Слабая упаковка объекта и потеря качественных лидов.',
                'Сделка с неподготовленным покупателем или непрозрачной схемой оплаты.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Подготовительный этап обычно занимает несколько дней. Срок продажи зависит от цены, формата объекта, конкуренции и качества спроса в выбранном сегменте.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Комиссия обсуждается до запуска объекта в работу и зависит от типа недвижимости, сложности сделки и объёма маркетинга. Все условия фиксируются заранее.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Можно ли продавать без эксклюзива?', 'answer': 'Да, но эксклюзивная модель обычно даёт более управляемый маркетинг и понятную ответственность сторон.'},
                {'question': 'Помогаете ли вы с ценообразованием?', 'answer': 'Да. Мы формируем рыночный коридор и объясняем, как цена влияет на скорость и качество спроса.'},
                {'question': 'Берёте ли вы на себя показы и переговоры?', 'answer': 'Да. Мы координируем показы, лиды и диалог с потенциальными покупателями.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Продажа с корректировкой цены', 'text': 'После аудита скорректировали позиционирование и цену, что помогло перевести объект из долгой экспозиции в активные переговоры.'},
                {'title': 'Выход из инвестиционного актива', 'text': 'Собрали пакет материалов для инвестора, нашли покупателя и структурировали сделку с прозрачным графиком расчётов.'},
            ],
            'cta_title': 'Подготовим стратегию продажи',
            'cta_text': 'Покажем рыночный коридор цены, оценим риски и предложим понятный сценарий вывода объекта на рынок.',
            'cta_button': 'Оценить продажу',
        },
        'en': {
            'badge': 'Property sale',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Owners often come to market without a pricing strategy, without strong packaging, and without a clear negotiation structure.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'Owners who want to sell without long and unproductive exposure.',
                'Investors who need to exit at a marketable price and within a realistic timeline.',
                'Sellers who want one accountable partner for marketing, showings, and negotiations.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Asset audit', 'text': 'We assess positioning, competition, liquidity, and the right pricing corridor.'},
                {'title': 'Packaging and marketing', 'text': 'We prepare visuals, copy, presentation materials, and launch marketing through relevant channels.'},
                {'title': 'Leads and showings', 'text': 'We qualify enquiries, coordinate viewings, and track market feedback.'},
                {'title': 'Negotiation and closing', 'text': 'We support the offer, reservation, payment structure, and final completion.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Ownership confirmation documents.',
                'Owner passport or company details.',
                'Layouts, technical specs, and ownership history.',
                'Information on encumbrances, payments, and the management company.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'Overpricing that kills demand and extends exposure time.',
                'Weak packaging that loses qualified buyers.',
                'Entering a deal with an unprepared buyer or an opaque payment structure.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'Preparation usually takes a few days. Sale timing depends on pricing, asset format, competition, and real demand in the chosen segment.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'Our fee is agreed before launch and depends on the property type, deal complexity, and marketing scope. Terms are fixed upfront.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Can the property be sold without an exclusive mandate?', 'answer': 'Yes, but an exclusive model usually gives clearer accountability and stronger marketing control.'},
                {'question': 'Do you help with pricing?', 'answer': 'Yes. We define a pricing corridor and explain how it affects speed and lead quality.'},
                {'question': 'Do you handle viewings and negotiations?', 'answer': 'Yes. We coordinate buyers, viewings, and the negotiation flow.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Sale after repricing', 'text': 'We repositioned the asset and adjusted pricing, moving it from stalled exposure into active negotiations.'},
                {'title': 'Investment exit', 'text': 'We packaged the asset for an investor buyer, sourced demand, and structured a transparent closing path.'},
            ],
            'cta_title': 'Let’s build your sale strategy',
            'cta_text': 'We will show the right market price range, assess the risks, and outline the best route to market.',
            'cta_button': 'Plan the sale',
        },
        'th': {
            'badge': 'การขายอสังหาริมทรัพย์',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'เจ้าของจำนวนมากนำทรัพย์ออกสู่ตลาดโดยไม่มีแผนราคา ไม่มีการแพ็กเกจทรัพย์ที่ชัดเจน และไม่มีโครงสร้างการเจรจาที่เหมาะสม.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'เจ้าของที่ต้องการขายโดยไม่ให้ทรัพย์ค้างตลาดนานเกินไป.',
                'นักลงทุนที่ต้องการ exit ในราคาตลาดและภายในกรอบเวลาที่สมเหตุสมผล.',
                'ผู้ขายที่ต้องการพาร์ตเนอร์คนเดียวที่ดูแลการตลาด การพาชม และการเจรจา.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'ตรวจสอบทรัพย์', 'text': 'ประเมิน positioning คู่แข่ง สภาพคล่อง และช่วงราคาที่เหมาะสม.'},
                {'title': 'แพ็กเกจและการตลาด', 'text': 'จัดทำภาพ ข้อความ และ material สำหรับการขาย พร้อมเปิดการตลาดในช่องทางที่เหมาะสม.'},
                {'title': 'ลีดและการพาชม', 'text': 'คัดกรองลีด จัดการนัดหมาย และเก็บ feedback จากตลาด.'},
                {'title': 'เจรจาและปิดดีล', 'text': 'ดูแล offer การจอง โครงสร้างการชำระเงิน และขั้นตอนปิดการขาย.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'เอกสารยืนยันกรรมสิทธิ์.',
                'หนังสือเดินทางของเจ้าของหรือข้อมูลบริษัทผู้ถือครอง.',
                'แบบแปลน รายละเอียดทางเทคนิค และประวัติการถือครอง.',
                'ข้อมูลภาระผูกพัน ค่าใช้จ่าย และบริษัทบริหารอาคารหรือโครงการ.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ตั้งราคาสูงเกินไปจนตลาดไม่ตอบสนอง.',
                'แพ็กเกจทรัพย์ไม่ดีพอและเสียลีดคุณภาพ.',
                'เข้าสู่ดีลกับผู้ซื้อที่ไม่พร้อมหรือมีโครงสร้างการชำระเงินไม่ชัดเจน.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'ขั้นตอนเตรียมการมักใช้เวลาไม่กี่วัน ส่วนระยะเวลาขายขึ้นอยู่กับราคา ประเภททรัพย์ การแข่งขัน และคุณภาพของดีมานด์ในตลาดนั้น.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'ค่าคอมมิชชั่นจะตกลงกันก่อนเริ่มงาน ขึ้นอยู่กับประเภททรัพย์ ความซับซ้อนของดีล และขอบเขตการตลาด โดยกำหนดเงื่อนไขล่วงหน้าอย่างชัดเจน.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'ขายแบบไม่ผูกเอ็กซ์คลูซีฟได้ไหม?', 'answer': 'ได้ แต่โมเดลเอ็กซ์คลูซีฟมักให้ความชัดเจนเรื่องความรับผิดชอบและการตลาดที่ควบคุมได้ดีกว่า.'},
                {'question': 'ช่วยตั้งราคาขายหรือไม่?', 'answer': 'ช่วย เรากำหนดช่วงราคาและอธิบายผลกระทบต่อความเร็วและคุณภาพของลีด.'},
                {'question': 'ดูแลพาชมและเจรจาหรือไม่?', 'answer': 'ดูแล เราประสานผู้ซื้อ นัดหมาย และกระบวนการเจรจาทั้งหมด.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'ขายได้หลังปรับราคา', 'text': 'เราปรับ positioning และช่วงราคา ทำให้ทรัพย์กลับเข้าสู่การเจรจาอย่างจริงจัง.'},
                {'title': 'ขายออกจากพอร์ตลงทุน', 'text': 'จัดทำ package สำหรับนักลงทุน หาผู้ซื้อ และวางโครงสร้างการปิดดีลที่โปร่งใส.'},
            ],
            'cta_title': 'วางกลยุทธ์การขายของคุณ',
            'cta_text': 'เราจะช่วยประเมินช่วงราคาตลาด วิเคราะห์ความเสี่ยง และกำหนดทางออกสู่ตลาดที่ชัดเจน.',
            'cta_button': 'ประเมินการขาย',
        },
    },
    'renting-property': {
        'ru': {
            'badge': 'Аренда недвижимости',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Арендатору сложно быстро найти подходящий объект, понять реальные условия и не потерять время на неподходящие варианты.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Тем, кто переезжает на Пхукет и хочет снять объект на понятных условиях.',
                'Семьям и удалённым специалистам, которым важны район, инфраструктура и сроки заезда.',
                'Клиентам, которые хотят сравнить long stay и short stay сценарии без лишних просмотров.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Формулируем запрос', 'text': 'Уточняем бюджет, район, срок аренды, состав семьи и обязательные параметры объекта.'},
                {'title': 'Подбор вариантов', 'text': 'Показываем только релевантные варианты с понятной ценой, условиями и требованиями собственника.'},
                {'title': 'Проверка условий', 'text': 'Разбираем депозит, коммунальные платежи, правила проживания и условия досрочного выезда.'},
                {'title': 'Заселение', 'text': 'Сопровождаем договор аренды, передачу объекта и финальную проверку условий перед заездом.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Паспорт арендатора.',
                'Контактные данные и сроки планируемого проживания.',
                'Иногда — подтверждение занятости или источника дохода.',
                'Для долгосрочной аренды — данные для договора и депозита.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Несоответствие объекта описанию и условиям по факту.',
                'Скрытые платежи, спорные условия депозита и коммунальных расходов.',
                'Потеря времени на неподходящие объекты и несистемный поиск.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Первые релевантные варианты можем подобрать в течение 1 дня. Итоговый срок зависит от сезона, района и типа недвижимости.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Условия нашей комиссии зависят от срока аренды, сложности подбора и структуры сделки. Все расходы объясняем заранее до бронирования или подписания договора.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Можно ли снять объект дистанционно?', 'answer': 'Да, если собственник и формат сделки это допускают. Мы заранее проговариваем риски и условия.'},
                {'question': 'Вы помогаете с long stay и short stay?', 'answer': 'Да, но мы всегда объясняем разницу по условиям, депозиту и гибкости договора.'},
                {'question': 'Проверяете ли вы договор аренды?', 'answer': 'Да, мы смотрим ключевые условия и подсказываем, на что обратить внимание до подписания.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Переезд семьи на Пхукет', 'text': 'Быстро подобрали дом в нужном районе рядом со школой и инфраструктурой, согласовали понятные условия депозита.'},
                {'title': 'Долгосрочная аренда для remote work', 'text': 'Отсортировали объекты по качеству интернета, району и бюджету, исключив лишние просмотры.'},
            ],
            'cta_title': 'Подберём аренду под ваш сценарий',
            'cta_text': 'Расскажите о сроке, районе и бюджете — мы подготовим варианты и объясним реальные условия аренды.',
            'cta_button': 'Подобрать аренду',
        },
        'en': {
            'badge': 'Property rental',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Renters often struggle to find a suitable property quickly, understand the real terms, and avoid wasting time on poor-fit options.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'People relocating to Phuket who want a clear and well-managed rental process.',
                'Families and remote professionals who care about district, infrastructure, and move-in timing.',
                'Clients comparing long-stay and short-stay scenarios without endless viewings.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Define the brief', 'text': 'We clarify budget, district, lease term, household profile, and non-negotiable property criteria.'},
                {'title': 'Curated selection', 'text': 'We present only relevant options with clear pricing, owner expectations, and occupancy terms.'},
                {'title': 'Terms review', 'text': 'We review deposit terms, utilities, house rules, and early move-out conditions.'},
                {'title': 'Move-in support', 'text': 'We support the tenancy agreement, handover, and final verification before check-in.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Tenant passport.',
                'Contact details and intended stay period.',
                'Sometimes proof of employment or source of income.',
                'For long-term rentals: agreement details and deposit information.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'A property that does not match the listing or promised terms.',
                'Hidden costs and unclear deposit or utility conditions.',
                'Wasted time on unsuitable listings and fragmented search processes.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'Relevant first options can usually be prepared within a day. Timing then depends on seasonality, district, and property type.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'Our fee structure depends on lease term, search complexity, and deal structure. We explain all costs before reservation or agreement signing.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Can I rent remotely?', 'answer': 'Yes, where the owner and transaction format allow it. We explain the risks and terms in advance.'},
                {'question': 'Do you help with both long stay and short stay?', 'answer': 'Yes, and we explain the differences in flexibility, deposit, and contract terms.'},
                {'question': 'Do you review the rental agreement?', 'answer': 'Yes. We review the key clauses and highlight what matters before signing.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Family relocation', 'text': 'We sourced a house near the right school and infrastructure and negotiated clear deposit conditions.'},
                {'title': 'Remote work rental', 'text': 'We filtered stock by internet quality, location, and budget, removing wasted viewings from the process.'},
            ],
            'cta_title': 'Let us source the right rental',
            'cta_text': 'Tell us your timing, preferred area, and budget, and we will prepare options with clear rental terms.',
            'cta_button': 'Find a rental',
        },
        'th': {
            'badge': 'การเช่าอสังหาริมทรัพย์',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'ผู้เช่ามักหาทรัพย์ที่ตรงความต้องการได้ยาก เข้าใจเงื่อนไขจริงไม่ครบ และเสียเวลากับตัวเลือกที่ไม่เหมาะสม.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'ผู้ที่ย้ายมาอยู่ภูเก็ตและต้องการกระบวนการเช่าที่ชัดเจน.',
                'ครอบครัวและผู้ทำงานระยะไกลที่ให้ความสำคัญกับเขต สิ่งอำนวยความสะดวก และเวลาย้ายเข้า.',
                'ลูกค้าที่ต้องการเปรียบเทียบ long stay และ short stay โดยไม่ต้องดูทรัพย์จำนวนมาก.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'กำหนด brief', 'text': 'ระบุงบประมาณ เขต ระยะเวลาเช่า ลักษณะผู้อยู่อาศัย และเงื่อนไขสำคัญของทรัพย์.'},
                {'title': 'คัดเลือกทรัพย์', 'text': 'นำเสนอเฉพาะตัวเลือกที่ตรงเงื่อนไข พร้อมราคาและข้อกำหนดของเจ้าของที่ชัดเจน.'},
                {'title': 'ตรวจสอบเงื่อนไข', 'text': 'ตรวจสอบเงินประกัน ค่าสาธารณูปโภค กฎการอยู่อาศัย และเงื่อนไขการย้ายออกก่อนกำหนด.'},
                {'title': 'ช่วยย้ายเข้า', 'text': 'ดูแลสัญญาเช่า การรับมอบทรัพย์ และตรวจสอบเงื่อนไขสุดท้ายก่อนเข้าอยู่.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'หนังสือเดินทางของผู้เช่า.',
                'ข้อมูลติดต่อและช่วงเวลาที่ต้องการเข้าพัก.',
                'บางกรณีอาจต้องมีหลักฐานการทำงานหรือรายได้.',
                'สำหรับ long-term rental: ข้อมูลสำหรับสัญญาและเงินประกัน.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ทรัพย์จริงไม่ตรงกับประกาศหรือเงื่อนไขที่แจ้งไว้.',
                'ค่าใช้จ่ายแฝงและเงื่อนไขเงินประกันที่ไม่ชัดเจน.',
                'เสียเวลากับตัวเลือกที่ไม่เหมาะสมและการค้นหาที่กระจัดกระจาย.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'โดยปกติสามารถคัดตัวเลือกชุดแรกได้ภายใน 1 วัน ส่วนความเร็วในการปิดดีลขึ้นอยู่กับฤดูกาล เขต และประเภททรัพย์.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'ค่าบริการขึ้นอยู่กับระยะเวลาเช่า ความซับซ้อนในการค้นหา และโครงสร้างดีล โดยเราจะอธิบายค่าใช้จ่ายทั้งหมดก่อนจองหรือเซ็นสัญญา.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'เช่าจากต่างประเทศได้ไหม?', 'answer': 'ได้ หากเจ้าของและรูปแบบดีลรองรับ เราจะอธิบายความเสี่ยงและเงื่อนไขให้ชัดเจนก่อน.'},
                {'question': 'ช่วยทั้ง long stay และ short stay หรือไม่?', 'answer': 'ช่วย และเราจะอธิบายความต่างด้านความยืดหยุ่น เงินประกัน และรูปแบบสัญญา.'},
                {'question': 'ช่วยตรวจสัญญาเช่าหรือไม่?', 'answer': 'ช่วย เราตรวจ clauses สำคัญและชี้จุดที่ควรดูให้ก่อนลงนาม.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'ครอบครัวย้ายมาอยู่ภูเก็ต', 'text': 'คัดบ้านในย่านที่เหมาะสมใกล้โรงเรียนและสิ่งอำนวยความสะดวก พร้อมต่อรองเงื่อนไขเงินประกัน.'},
                {'title': 'เช่าระยะยาวสำหรับ remote work', 'text': 'กรองทรัพย์ตามคุณภาพอินเทอร์เน็ต ทำเล และงบประมาณ ลดการพาชมที่ไม่จำเป็น.'},
            ],
            'cta_title': 'ให้เราหาบ้านเช่าที่เหมาะกับคุณ',
            'cta_text': 'บอกช่วงเวลา ทำเล และงบประมาณของคุณ แล้วเราจะคัดตัวเลือกพร้อมเงื่อนไขที่ชัดเจนให้.',
            'cta_button': 'หาบ้านเช่า',
        },
    },
    'commercial-real-estate': {
        'ru': {
            'badge': 'Коммерческая недвижимость',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Покупателю или арендатору коммерческого объекта важно не только найти помещение, но и понять трафик, бизнес-модель, юридические ограничения и окупаемость.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Инвесторам, которые рассматривают готовый бизнес или коммерческий объект на Пхукете.',
                'Предпринимателям, которым нужно помещение под собственный операционный формат.',
                'Клиентам, которым важна оценка локации, потока клиентов и договорных условий.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Постановка задачи', 'text': 'Определяем формат бизнеса, целевую локацию, бюджет и критерии рентабельности.'},
                {'title': 'Подбор вариантов', 'text': 'Сравниваем коммерческие объекты по локации, трафику, конфигурации и потенциалу дохода.'},
                {'title': 'Due diligence', 'text': 'Проверяем правовой статус, условия аренды или собственности, ограничения и операционные риски.'},
                {'title': 'Сделка и запуск', 'text': 'Сопровождаем переговоры, договоры, передачу объекта и следующий этап запуска или интеграции.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Паспорт или регистрационные данные компании.',
                'Понимание операционной модели и требований к помещению.',
                'По готовому бизнесу — финансовые вводные, данные по аренде, лицензиям и персоналу.',
                'По покупке — документы собственника и объектовая документация.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Покупка объекта без оценки операционной модели и реального клиентского потока.',
                'Ошибки в договорной структуре, сроках аренды и ограничениях использования помещения.',
                'Переоценка доходности и недооценка затрат на запуск или адаптацию объекта.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Срок подбора зависит от ниши и требований к локации. На due diligence и переговоры обычно требуется больше времени, чем в жилом сегменте.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Комиссия и формат сопровождения зависят от типа сделки, наличия готового бизнеса, объёма проверки и переговорного процесса.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Вы помогаете только с покупкой?', 'answer': 'Нет. Мы работаем и с покупкой, и с арендой, если задача связана с коммерческой недвижимостью или бизнесом.'},
                {'question': 'Проверяете ли вы цифры и договоры?', 'answer': 'Да, в рамках доступных данных мы смотрим договорную структуру, расходы, ограничения и риски.'},
                {'question': 'Можно ли подобрать помещение под конкретный формат бизнеса?', 'answer': 'Да. Мы начинаем с формата бизнеса и уже от него строим критерии подбора.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Подбор помещения под операционный бизнес', 'text': 'Сравнили несколько локаций, учли поток клиентов и помогли выбрать объект с лучшими условиями запуска.'},
                {'title': 'Анализ готового бизнеса', 'text': 'Разобрали вводные по активу, выявили узкие места в модели и помогли клиенту скорректировать сценарий сделки.'},
            ],
            'cta_title': 'Разберём коммерческий сценарий',
            'cta_text': 'Опишите формат бизнеса или инвестиционную задачу, а мы подготовим релевантные объекты и покажем ключевые риски сделки.',
            'cta_button': 'Обсудить задачу',
        },
        'en': {
            'badge': 'Commercial real estate',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Commercial clients need more than just a property match; they also need clarity on footfall, business model fit, legal restrictions, and profitability.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'Investors considering a going concern or commercial asset in Phuket.',
                'Operators looking for premises for their own business model.',
                'Clients who need location, customer flow, and contractual conditions assessed before commitment.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Task definition', 'text': 'We define business format, target area, budget, and commercial return criteria.'},
                {'title': 'Selection', 'text': 'We compare options by location, footfall, configuration, and income potential.'},
                {'title': 'Due diligence', 'text': 'We review legal status, ownership or lease structure, restrictions, and operating risks.'},
                {'title': 'Deal and launch', 'text': 'We support negotiations, contracts, handover, and the next stage of launch or integration.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Passport or company registration details.',
                'A clear outline of the operating model and premises requirements.',
                'For going concerns: basic financials, lease data, licences, and staffing information.',
                'For acquisitions: ownership documents and property file.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'Buying or leasing without validating the operating model and real footfall.',
                'Weak contract structure, lease term issues, or use restrictions.',
                'Overestimating income while underestimating launch or adaptation costs.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'Selection timing depends on niche and location criteria. Due diligence and negotiation usually take longer than in residential deals.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'The fee structure depends on the type of deal, whether a going concern is involved, and the scope of review and negotiation required.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Do you only assist with purchases?', 'answer': 'No. We support both purchase and lease scenarios for commercial real estate and related businesses.'},
                {'question': 'Do you review numbers and contracts?', 'answer': 'Yes. Based on available data, we review costs, structure, restrictions, and key commercial risks.'},
                {'question': 'Can you source space for a specific business model?', 'answer': 'Yes. We start with the operating format and build the selection criteria from there.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Premises for an operating business', 'text': 'We compared several areas, assessed footfall, and helped the client choose the location with the strongest launch conditions.'},
                {'title': 'Going concern review', 'text': 'We analysed the asset inputs, highlighted weak points in the model, and helped the client reshape the transaction strategy.'},
            ],
            'cta_title': 'Let’s review your commercial brief',
            'cta_text': 'Share the business format or investment thesis, and we will prepare relevant options and highlight the key deal risks.',
            'cta_button': 'Discuss the brief',
        },
        'th': {
            'badge': 'อสังหาริมทรัพย์เชิงพาณิชย์',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'ลูกค้าฝั่งเชิงพาณิชย์ไม่ได้ต้องการแค่ทรัพย์ที่ตรง brief แต่ต้องเข้าใจ traffic รูปแบบธุรกิจ ข้อจำกัดทางกฎหมาย และความคุ้มค่าทางการเงินด้วย.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'นักลงทุนที่สนใจธุรกิจพร้อมดำเนินการหรือทรัพย์เชิงพาณิชย์ในภูเก็ต.',
                'ผู้ประกอบการที่ต้องการพื้นที่สำหรับโมเดลธุรกิจของตัวเอง.',
                'ลูกค้าที่ต้องการประเมินทำเล ปริมาณลูกค้า และเงื่อนไขสัญญาก่อนตัดสินใจ.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'กำหนดโจทย์', 'text': 'กำหนดรูปแบบธุรกิจ ทำเลเป้าหมาย งบประมาณ และเกณฑ์ผลตอบแทน.'},
                {'title': 'คัดเลือกตัวเลือก', 'text': 'เปรียบเทียบทรัพย์ตามทำเล traffic การจัดผัง และศักยภาพในการสร้างรายได้.'},
                {'title': 'Due diligence', 'text': 'ตรวจสถานะทางกฎหมาย โครงสร้างสิทธิ เงื่อนไขเช่า และความเสี่ยงการดำเนินงาน.'},
                {'title': 'ดีลและการเริ่มต้น', 'text': 'ช่วยเจรจา สัญญา การรับมอบ และขั้นตอนต่อเนื่องก่อนเปิดดำเนินงาน.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'หนังสือเดินทางหรือข้อมูลจดทะเบียนบริษัท.',
                'ข้อมูลรูปแบบธุรกิจและความต้องการของพื้นที่.',
                'สำหรับธุรกิจพร้อมดำเนินการ: ข้อมูลการเงิน ค่าเช่า ใบอนุญาต และทีมงาน.',
                'สำหรับการซื้อ: เอกสารกรรมสิทธิ์และแฟ้มข้อมูลทรัพย์.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ซื้อหรือเช่าโดยไม่ประเมินโมเดลธุรกิจและ traffic จริง.',
                'ข้อผิดพลาดด้านโครงสร้างสัญญา ระยะเวลาเช่า หรือข้อจำกัดการใช้งาน.',
                'ประเมินรายได้สูงเกินจริงและมองต้นทุนเปิดดำเนินงานต่ำเกินไป.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'ระยะเวลาคัดเลือกขึ้นอยู่กับ niche และเงื่อนไขของทำเล ขณะที่ due diligence และการเจรจามักใช้เวลามากกว่าทรัพย์พักอาศัย.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'โครงสร้างค่าบริการขึ้นอยู่กับประเภทดีล การมีธุรกิจพร้อมดำเนินการ และขอบเขตของการตรวจสอบและเจรจา.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'ช่วยเฉพาะการซื้อหรือไม่?', 'answer': 'ไม่ เราช่วยทั้งการซื้อและการเช่าที่เกี่ยวกับอสังหาริมทรัพย์เชิงพาณิชย์หรือธุรกิจ.'},
                {'question': 'ช่วยดูตัวเลขและสัญญาหรือไม่?', 'answer': 'ช่วย เราตรวจค่าใช้จ่าย โครงสร้าง ข้อจำกัด และความเสี่ยงเชิงพาณิชย์จากข้อมูลที่มี.'},
                {'question': 'สามารถหาพื้นที่ตามรูปแบบธุรกิจเฉพาะได้ไหม?', 'answer': 'ได้ เราเริ่มจากโมเดลธุรกิจและสร้างเกณฑ์คัดเลือกจากตรงนั้น.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'คัดพื้นที่สำหรับธุรกิจปฏิบัติการ', 'text': 'เปรียบเทียบหลายทำเล ประเมิน traffic และช่วยเลือกทรัพย์ที่พร้อมเริ่มต้นได้ดีที่สุด.'},
                {'title': 'วิเคราะห์ธุรกิจพร้อมดำเนินการ', 'text': 'ตรวจข้อมูลเบื้องต้นของดีล ชี้จุดเสี่ยงในโมเดล และช่วยปรับกลยุทธ์การเข้าซื้อ.'},
            ],
            'cta_title': 'มาคุยโจทย์เชิงพาณิชย์ของคุณ',
            'cta_text': 'บอกรูปแบบธุรกิจหรือ thesis การลงทุนของคุณ แล้วเราจะช่วยคัดตัวเลือกและชี้ความเสี่ยงสำคัญของดีล.',
            'cta_button': 'คุยโจทย์ธุรกิจ',
        },
    },
    'land-sale': {
        'ru': {
            'badge': 'Продажа земли',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Сделки с землёй требуют более точной проверки статуса участка, ограничений использования, доступа, инфраструктуры и инвестиционного сценария.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Инвесторам, которые рассматривают покупку земли на Пхукете или в соседних провинциях.',
                'Девелоперам и частным клиентам, которым нужен участок под строительство.',
                'Собственникам, которым нужен профессиональный вывод участка на рынок.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Постановка задачи', 'text': 'Определяем цель: инвестиция, застройка, перепродажа или долгосрочное владение.'},
                {'title': 'Подбор / аудит участка', 'text': 'Смотрим локацию, доступ, рельеф, инфраструктуру, назначение и окружение.'},
                {'title': 'Проверка и согласование', 'text': 'Проверяем документы, правовой статус, ограничения использования и условия сделки.'},
                {'title': 'Сделка', 'text': 'Сопровождаем переговоры, договоры, расчёты и последующие шаги после закрытия.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Правоустанавливающие документы на землю.',
                'Кадастровая и картографическая информация по участку.',
                'Данные по доступу, коммуникациям и ограничениям использования.',
                'Планируемый сценарий покупки или продажи.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Покупка участка без понимания ограничений по использованию и доступу.',
                'Переоценка инвестиционного потенциала и ликвидности локации.',
                'Юридические и инфраструктурные ограничения, которые не были проверены заранее.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Сроки зависят от размера участка, статуса документов и сложности проверки. Земельные сделки почти всегда требуют больше времени на верификацию.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Комиссия и объём сопровождения зависят от типа участка, географии, структуры сделки и глубины проверки перед покупкой или продажей.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Работаете ли вы только по Пхукету?', 'answer': 'Основной фокус — Пхукет, но в зависимости от задачи можем помочь и по соседним направлениям, включая Краби.'},
                {'question': 'Проверяете ли вы юридический статус участка?', 'answer': 'Да. Мы помогаем организовать предварительную проверку и понять ограничения до выхода в сделку.'},
                {'question': 'Можно ли подобрать землю под конкретный проект?', 'answer': 'Да. Мы начинаем с параметров проекта и уже под них подбираем релевантные участки.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Участок под девелопмент', 'text': 'Сравнили несколько участков, отсеяли слабые по доступу и ограничениям, помогли клиенту сфокусироваться на реалистичном варианте.'},
                {'title': 'Инвестиционная покупка земли', 'text': 'Оценили локацию, сценарий роста и параметры ликвидности, чтобы клиент входил в сделку осознанно.'},
            ],
            'cta_title': 'Обсудим участок или стратегию продажи',
            'cta_text': 'Расскажите, нужен ли вам участок под проект или вы хотите вывести землю на рынок — мы поможем выстроить безопасный сценарий сделки.',
            'cta_button': 'Обсудить землю',
        },
        'en': {
            'badge': 'Land sale',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Land deals require deeper validation of title status, permitted use, access, infrastructure, and investment logic than standard residential transactions.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'Investors considering land acquisition in Phuket or nearby provinces.',
                'Developers and private buyers who need land for construction.',
                'Owners who want a professional market strategy for a plot sale.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Define the brief', 'text': 'We clarify whether the objective is investment, development, resale, or long-term holding.'},
                {'title': 'Selection / land audit', 'text': 'We assess location, access, topography, infrastructure, permitted use, and surrounding context.'},
                {'title': 'Checks and alignment', 'text': 'We review documents, legal status, use restrictions, and deal conditions.'},
                {'title': 'Execution', 'text': 'We support negotiations, contracts, payments, and next steps after completion.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Land title and ownership documents.',
                'Cadastre and mapping information for the plot.',
                'Details on access, utilities, and use limitations.',
                'The intended buy or sell scenario.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'Acquiring land without understanding use restrictions or access issues.',
                'Overestimating the investment potential or liquidity of the location.',
                'Legal or infrastructure constraints that were not checked early enough.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'Timing depends on plot size, document readiness, and the complexity of review. Land transactions usually require more validation time than residential deals.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'Fees and scope depend on plot type, geography, transaction structure, and the depth of pre-deal review required.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Do you work only in Phuket?', 'answer': 'Phuket is our main focus, but depending on the brief we can also support nearby areas, including Krabi.'},
                {'question': 'Do you review the legal status of the land?', 'answer': 'Yes. We help organise early checks so restrictions and practical issues are understood before the deal.'},
                {'question': 'Can you source land for a specific project?', 'answer': 'Yes. We start from the project brief and screen plots against those parameters.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Development site selection', 'text': 'We reviewed several plots, ruled out weak options on access and restrictions, and helped focus on a realistic candidate.'},
                {'title': 'Investment land acquisition', 'text': 'We assessed location dynamics, growth logic, and liquidity to support a more disciplined entry.'},
            ],
            'cta_title': 'Let’s discuss the plot or sale strategy',
            'cta_text': 'Tell us whether you need land for a project or want to bring a plot to market, and we will map out a safer transaction path.',
            'cta_button': 'Discuss land',
        },
        'th': {
            'badge': 'การซื้อขายที่ดิน',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'ดีลที่ดินต้องตรวจสอบสถานะเอกสาร ข้อจำกัดการใช้ทางเข้าออก โครงสร้างพื้นฐาน และตรรกะการลงทุนอย่างละเอียดกว่าทรัพย์ที่อยู่อาศัยทั่วไป.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'นักลงทุนที่สนใจซื้อที่ดินในภูเก็ตหรือจังหวัดใกล้เคียง.',
                'ผู้พัฒนาและผู้ซื้อส่วนบุคคลที่ต้องการที่ดินสำหรับการก่อสร้าง.',
                'เจ้าของที่ดินที่ต้องการกลยุทธ์นำทรัพย์ออกสู่ตลาดอย่างเป็นมืออาชีพ.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'กำหนดโจทย์', 'text': 'กำหนดว่าเป้าหมายคือการลงทุน การพัฒนา การขายต่อ หรือถือครองระยะยาว.'},
                {'title': 'คัดเลือก / audit ที่ดิน', 'text': 'ประเมินทำเล ทางเข้าออก ลักษณะภูมิประเทศ โครงสร้างพื้นฐาน และข้อกำหนดการใช้ประโยชน์.'},
                {'title': 'ตรวจสอบและตกลงเงื่อนไข', 'text': 'ตรวจเอกสาร สถานะทางกฎหมาย ข้อจำกัด และเงื่อนไขของดีล.'},
                {'title': 'ปิดดีล', 'text': 'ช่วยเจรจา สัญญา การชำระเงิน และขั้นตอนต่อเนื่องหลังปิดดีล.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'เอกสารสิทธิ์และกรรมสิทธิ์ในที่ดิน.',
                'ข้อมูลแผนที่และข้อมูลที่ดินจากหน่วยงานที่เกี่ยวข้อง.',
                'ข้อมูลทางเข้าออก สาธารณูปโภค และข้อจำกัดการใช้ประโยชน์.',
                'เป้าหมายการซื้อหรือการขายที่ดิน.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ซื้อที่ดินโดยไม่เข้าใจข้อจำกัดการใช้หรือปัญหาทางเข้าออก.',
                'ประเมินศักยภาพการลงทุนหรือสภาพคล่องของทำเลสูงเกินจริง.',
                'ข้อจำกัดด้านกฎหมายหรือโครงสร้างพื้นฐานที่ไม่ได้ตรวจสอบล่วงหน้า.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'ระยะเวลาขึ้นอยู่กับขนาดที่ดิน ความพร้อมของเอกสาร และความซับซ้อนของการตรวจสอบ โดยดีลที่ดินมักต้องใช้เวลาตรวจมากกว่าทรัพย์ที่อยู่อาศัย.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'ค่าบริการและขอบเขตงานขึ้นอยู่กับประเภทของที่ดิน พื้นที่ โครงสร้างดีล และระดับการตรวจสอบที่ต้องการก่อนซื้อหรือขาย.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'ดูแลเฉพาะภูเก็ตหรือไม่?', 'answer': 'โฟกัสหลักคือภูเก็ต แต่ตาม brief เราสามารถช่วยในพื้นที่ใกล้เคียง เช่น กระบี่ ได้เช่นกัน.'},
                {'question': 'ช่วยตรวจสถานะทางกฎหมายของที่ดินหรือไม่?', 'answer': 'ช่วย เราช่วยจัดกระบวนการตรวจสอบเบื้องต้นเพื่อให้เข้าใจข้อจำกัดก่อนทำดีล.'},
                {'question': 'สามารถหาที่ดินตามโปรเจกต์เฉพาะได้ไหม?', 'answer': 'ได้ เราเริ่มจาก brief ของโครงการและคัดเลือกแปลงที่ตรงเงื่อนไข.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'คัดเลือกที่ดินสำหรับการพัฒนา', 'text': 'เปรียบเทียบหลายแปลง ตัดตัวเลือกที่อ่อนเรื่องทางเข้าออกและข้อจำกัด และช่วยโฟกัสแปลงที่ใช้งานได้จริง.'},
                {'title': 'ซื้อที่ดินเพื่อการลงทุน', 'text': 'ประเมินการเติบโตของทำเลและสภาพคล่อง เพื่อให้ลูกค้าเข้าดีลอย่างมีข้อมูล.'},
            ],
            'cta_title': 'มาคุยเรื่องที่ดินหรือกลยุทธ์การขาย',
            'cta_text': 'บอกเราว่าคุณต้องการซื้อที่ดินสำหรับโครงการหรือกำลังจะขายแปลงที่ถืออยู่ แล้วเราจะช่วยวางเส้นทางดีลที่ปลอดภัยกว่า.',
            'cta_button': 'คุยเรื่องที่ดิน',
        },
    },
    'legal-services': {
        'ru': {
            'badge': 'Юридическое сопровождение',
            'overview_title': 'Что включает услуга',
            'problem_title': 'Проблема клиента',
            'problem_text': 'Даже хороший объект может стать проблемной сделкой, если клиент не понимает договорную структуру, ограничения владения и порядок оформления в Таиланде.',
            'audience_title': 'Кому подходит услуга',
            'audience_items': [
                'Покупателям, которым нужна безопасная структура сделки и понятное оформление.',
                'Инвесторам, которые хотят проверить договоры, риски и обязательства до оплаты.',
                'Клиентам, которые хотят пройти сделку без юридических сюрпризов и спорных условий.',
            ],
            'stages_title': 'Этапы работы',
            'stages': [
                {'title': 'Разбор задачи', 'text': 'Понимаем тип сделки, структуру владения и основные вопросы клиента.'},
                {'title': 'Проверка документов', 'text': 'Смотрим договоры, статус объекта, ограничения и ключевые обязательства сторон.'},
                {'title': 'Рекомендации и согласование', 'text': 'Объясняем риски, предлагаем безопасную структуру и помогаем согласовать спорные условия.'},
                {'title': 'Сопровождение до закрытия', 'text': 'Остаёмся в процессе до подписания и финального оформления документов.'},
            ],
            'documents_title': 'Какие документы обычно нужны',
            'documents': [
                'Паспорт клиента и данные по стороне сделки.',
                'Проект договора или reservation agreement.',
                'Документы по объекту, ownership structure и платежному графику.',
                'Любые приложения, письма и условия, влияющие на сделку.',
            ],
            'risks_title': 'Какие риски мы закрываем',
            'risks': [
                'Подписание договора с невыгодными или неочевидными обязательствами.',
                'Непонимание правовой структуры владения и ограничений для иностранного покупателя.',
                'Ошибки в сроках, штрафах, расчётах и порядке передачи объекта.',
            ],
            'timeline_title': 'Сроки',
            'timeline_text': 'Первичный разбор документов возможен быстро, но общий срок зависит от объёма материала, структуры сделки и количества раундов согласования.',
            'pricing_title': 'Стоимость / комиссия',
            'pricing_text': 'Стоимость зависит от сложности сделки, количества документов и глубины сопровождения. Формат работы и бюджет обсуждаются заранее.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Вы заменяете местного юриста?', 'answer': 'Мы не подменяем профильного юриста в сложных кейсах, но организуем понятную структуру проверки и сопровождения вместе с профильными специалистами.'},
                {'question': 'Можно ли подключить вас только на проверку договора?', 'answer': 'Да, мы можем подключиться точечно, если клиенту нужен аудит документа или структуры сделки.'},
                {'question': 'Помогаете ли вы понять ограничения для иностранцев?', 'answer': 'Да, это одна из ключевых частей сопровождения перед входом в сделку.'},
            ],
            'cases_title': 'Кейсы',
            'cases': [
                {'title': 'Проверка сделки до оплаты', 'text': 'До подписания выявили спорные условия договора и помогли клиенту скорректировать структуру обязательств.'},
                {'title': 'Сопровождение иностранного покупателя', 'text': 'Разложили по шагам порядок оформления, ограничения и документы, чтобы клиент понимал весь маршрут сделки.'},
            ],
            'cta_title': 'Проверим юридическую сторону сделки',
            'cta_text': 'Отправьте ваш вопрос или документы, и мы поможем понять риски, структуру и безопасный порядок действий.',
            'cta_button': 'Проверить сделку',
        },
        'en': {
            'badge': 'Legal support',
            'overview_title': 'What the service includes',
            'problem_title': 'Client problem',
            'problem_text': 'Even a strong property can become a problematic deal if the client does not understand the contract structure, ownership limits, and completion process in Thailand.',
            'audience_title': 'Who this service is for',
            'audience_items': [
                'Buyers who want a safer transaction structure and a clear completion path.',
                'Investors who need contracts, risks, and obligations reviewed before payment.',
                'Clients who want to avoid legal surprises and unclear terms during the deal.',
            ],
            'stages_title': 'Process',
            'stages': [
                {'title': 'Scope review', 'text': 'We define the transaction type, ownership structure, and the client’s main concerns.'},
                {'title': 'Document review', 'text': 'We review agreements, property status, restrictions, and the parties’ key obligations.'},
                {'title': 'Recommendations and negotiation', 'text': 'We explain the risks, propose a safer structure, and support discussions on disputed clauses.'},
                {'title': 'Support through closing', 'text': 'We stay involved until signing and final completion documents are in place.'},
            ],
            'documents_title': 'Typical documents required',
            'documents': [
                'Client passport and counterparty details.',
                'Draft agreement or reservation agreement.',
                'Property documents, ownership structure, and payment schedule.',
                'Any annexes, emails, or special conditions affecting the transaction.',
            ],
            'risks_title': 'Key risks we reduce',
            'risks': [
                'Signing documents with unfavourable or unclear obligations.',
                'Misunderstanding ownership structures and restrictions for foreign buyers.',
                'Errors in deadlines, penalties, payment mechanics, and handover terms.',
            ],
            'timeline_title': 'Timeline',
            'timeline_text': 'An initial document review can be done quickly, but the overall timing depends on document volume, deal structure, and the number of negotiation rounds.',
            'pricing_title': 'Cost / commission',
            'pricing_text': 'Pricing depends on deal complexity, document volume, and the depth of support required. Scope and budget are agreed in advance.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'Do you replace a local lawyer?', 'answer': 'No. In complex cases we coordinate a clear review structure with specialist legal counsel rather than replacing them.'},
                {'question': 'Can you step in just for contract review?', 'answer': 'Yes. We can provide focused support when the client only needs agreement or structure review.'},
                {'question': 'Do you explain foreign ownership restrictions?', 'answer': 'Yes. That is one of the key parts of our legal support before a deal is signed.'},
            ],
            'cases_title': 'Cases',
            'cases': [
                {'title': 'Pre-payment review', 'text': 'We identified disputed clauses before signing and helped the client reshape the obligations in the agreement.'},
                {'title': 'Foreign buyer support', 'text': 'We mapped the completion path, ownership restrictions, and documents so the client understood the full transaction route.'},
            ],
            'cta_title': 'Let us review the legal side of the deal',
            'cta_text': 'Send us your question or documents, and we will help you understand the risks, structure, and safest next steps.',
            'cta_button': 'Review the deal',
        },
        'th': {
            'badge': 'การสนับสนุนด้านกฎหมาย',
            'overview_title': 'บริการนี้ครอบคลุมอะไรบ้าง',
            'problem_title': 'ปัญหาของลูกค้า',
            'problem_text': 'แม้ทรัพย์จะดี แต่ดีลอาจมีปัญหาได้หากลูกค้าไม่เข้าใจโครงสร้างสัญญา ข้อจำกัดการถือครอง และขั้นตอนการโอนในประเทศไทย.',
            'audience_title': 'เหมาะกับใคร',
            'audience_items': [
                'ผู้ซื้อที่ต้องการโครงสร้างดีลที่ปลอดภัยและขั้นตอนปิดดีลที่ชัดเจน.',
                'นักลงทุนที่ต้องการให้ตรวจสัญญา ความเสี่ยง และภาระผูกพันก่อนชำระเงิน.',
                'ลูกค้าที่ต้องการหลีกเลี่ยงเงื่อนไขทางกฎหมายที่ไม่ชัดเจนหรือเป็นภาระเกินควร.',
            ],
            'stages_title': 'ขั้นตอนการทำงาน',
            'stages': [
                {'title': 'กำหนดขอบเขต', 'text': 'ทำความเข้าใจประเภทดีล โครงสร้างการถือครอง และคำถามหลักของลูกค้า.'},
                {'title': 'ตรวจเอกสาร', 'text': 'ตรวจสัญญา สถานะทรัพย์ ข้อจำกัด และหน้าที่หลักของแต่ละฝ่าย.'},
                {'title': 'ให้คำแนะนำและช่วยเจรจา', 'text': 'อธิบายความเสี่ยง เสนอทางเลือกที่ปลอดภัยกว่า และช่วยตกลง clauses ที่มีข้อกังวล.'},
                {'title': 'ดูแลจนจบดีล', 'text': 'ติดตามกระบวนการจนถึงการลงนามและเอกสารปิดดีลครบถ้วน.'},
            ],
            'documents_title': 'เอกสารที่มักต้องใช้',
            'documents': [
                'หนังสือเดินทางของลูกค้าและข้อมูลคู่สัญญา.',
                'ร่างสัญญาหรือ reservation agreement.',
                'เอกสารทรัพย์ โครงสร้างการถือครอง และแผนการชำระเงิน.',
                'ภาคผนวก อีเมล หรือเงื่อนไขพิเศษที่มีผลต่อดีล.',
            ],
            'risks_title': 'ความเสี่ยงที่เราช่วยลด',
            'risks': [
                'ลงนามสัญญาที่มีภาระผูกพันไม่เป็นธรรมหรือไม่ชัดเจน.',
                'ไม่เข้าใจโครงสร้างการถือครองและข้อจำกัดสำหรับผู้ซื้อชาวต่างชาติ.',
                'ข้อผิดพลาดด้านกำหนดเวลา ค่าปรับ การชำระเงิน และเงื่อนไขการส่งมอบ.',
            ],
            'timeline_title': 'ระยะเวลา',
            'timeline_text': 'การตรวจเอกสารเบื้องต้นสามารถทำได้ค่อนข้างเร็ว แต่ระยะเวลารวมขึ้นอยู่กับจำนวนเอกสาร โครงสร้างดีล และจำนวนรอบการเจรจา.',
            'pricing_title': 'ค่าใช้จ่าย / ค่าคอมมิชชั่น',
            'pricing_text': 'ค่าบริการขึ้นอยู่กับความซับซ้อนของดีล จำนวนเอกสาร และระดับการสนับสนุนที่ต้องการ โดยตกลงขอบเขตและงบประมาณล่วงหน้า.',
            'faq_title': 'FAQ',
            'faq': [
                {'question': 'บริการนี้แทนทนายท้องถิ่นหรือไม่?', 'answer': 'ไม่ ในดีลที่ซับซ้อนเราจะจัดโครงสร้างการตรวจสอบร่วมกับผู้เชี่ยวชาญด้านกฎหมายที่เกี่ยวข้อง ไม่ได้แทนที่พวกเขา.'},
                {'question': 'ช่วยเฉพาะตรวจสัญญาได้ไหม?', 'answer': 'ได้ เราสามารถเข้าไปช่วยเฉพาะจุดเมื่อจำเป็นต้องตรวจสัญญาหรือโครงสร้างดีล.'},
                {'question': 'ช่วยอธิบายข้อจำกัดสำหรับชาวต่างชาติหรือไม่?', 'answer': 'ช่วย นี่เป็นหนึ่งในส่วนสำคัญของการสนับสนุนก่อนลงนามดีล.'},
            ],
            'cases_title': 'ตัวอย่างเคส',
            'cases': [
                {'title': 'ตรวจดีลก่อนชำระเงิน', 'text': 'เราพบ clauses ที่มีข้อกังวลก่อนลงนามและช่วยปรับโครงสร้างภาระผูกพันในสัญญา.'},
                {'title': 'สนับสนุนผู้ซื้อชาวต่างชาติ', 'text': 'อธิบายขั้นตอนปิดดีล ข้อจำกัดการถือครอง และเอกสารที่จำเป็นให้เข้าใจเป็นลำดับ.'},
            ],
            'cta_title': 'ให้เราตรวจด้านกฎหมายของดีล',
            'cta_text': 'ส่งคำถามหรือเอกสารมาให้เรา แล้วเราจะช่วยอธิบายความเสี่ยง โครงสร้าง และขั้นตอนที่ปลอดภัยกว่า.',
            'cta_button': 'ตรวจดีล',
        },
    },
}


SERVICE_FAQ_EXTENSIONS = {
    'buying-property': {
        'ru': [
            {'question': 'Какие расходы нужно учитывать кроме цены объекта?', 'answer': 'Обычно отдельно проверяем налоги и сборы при оформлении, юридическое сопровождение, платежи управляющей компании, фонд обслуживания, мебель, ремонт и расходы на перевод средств. Итоговый список зависит от объекта и структуры сделки.'},
            {'question': 'Как понять, что цена объекта рыночная?', 'answer': 'Мы сравниваем объект с похожими предложениями по району, типу недвижимости, стадии готовности, площади, состоянию и условиям оплаты. Важно смотреть не только цену за метр, но и ликвидность, вид, инфраструктуру и качество проекта.'},
            {'question': 'Что лучше выбрать: новостройку или resale?', 'answer': 'Зависит от цели. Новостройка может подойти под поэтапную оплату и выбор планировки, resale чаще удобнее для быстрого въезда или оценки реального состояния. Мы сравниваем оба сценария по срокам, рискам, бюджету и ликвидности.'},
        ],
        'en': [
            {'question': 'What costs should I consider besides the property price?', 'answer': 'We usually check transfer taxes and fees, legal support, management fees, sinking fund, furniture, renovation needs, and fund transfer costs. The final list depends on the property and transaction structure.'},
            {'question': 'How do I know whether the price is realistic?', 'answer': 'We compare the property with similar listings by area, property type, completion stage, size, condition, and payment terms. Price per square metre matters, but liquidity, view, infrastructure, and project quality matter too.'},
            {'question': 'Should I choose a new development or resale property?', 'answer': 'It depends on the goal. New developments may suit phased payments and layout choice, while resale is often better for faster move-in and checking real condition. We compare both routes by timing, risk, budget, and liquidity.'},
        ],
        'th': [
            {'question': 'ควรเผื่องบอะไรนอกจากราคาทรัพย์?', 'answer': 'โดยปกติเราจะตรวจภาษีและค่าธรรมเนียมโอน ค่าใช้จ่ายด้านกฎหมาย ค่าส่วนกลาง เงินกองทุน เฟอร์นิเจอร์ งานปรับปรุง และต้นทุนการโอนเงิน รายการจริงขึ้นอยู่กับทรัพย์และโครงสร้างดีล.'},
            {'question': 'จะรู้ได้อย่างไรว่าราคาสมเหตุสมผล?', 'answer': 'เราเปรียบเทียบกับทรัพย์ใกล้เคียงตามทำเล ประเภททรัพย์ สถานะก่อสร้าง พื้นที่ สภาพทรัพย์ และเงื่อนไขการชำระเงิน โดยไม่ได้ดูแค่ราคาต่อตารางเมตร แต่ดูสภาพคล่อง วิว โครงสร้างพื้นฐาน และคุณภาพโครงการด้วย.'},
            {'question': 'ควรเลือกโครงการใหม่หรือ resale?', 'answer': 'ขึ้นอยู่กับเป้าหมาย โครงการใหม่อาจเหมาะกับการผ่อนชำระเป็นงวดและเลือกแบบห้อง ส่วน resale มักเหมาะกับการเข้าอยู่เร็วและเห็นสภาพจริง เราจะเปรียบเทียบทั้งสองทางเลือกตามเวลา ความเสี่ยง งบประมาณ และสภาพคล่อง.'},
        ],
    },
    'selling-property': {
        'ru': [
            {'question': 'Какие материалы нужны перед запуском продажи?', 'answer': 'Нужны документы по объекту, актуальные фото или возможность организовать съёмку, планировки, данные о платежах, управляющей компании, обременениях и желаемом сценарии продажи.'},
            {'question': 'Сколько времени занимает продажа недвижимости?', 'answer': 'Фиксированного срока нет: он зависит от цены, района, состояния объекта, конкуренции и качества спроса. Мы оцениваем реалистичный коридор экспозиции до запуска и корректируем стратегию по реакции рынка.'},
            {'question': 'Что делать, если объект уже долго не продаётся?', 'answer': 'Сначала разбираем цену, позиционирование, фотографии, описание, каналы продвижения и качество лидов. Часто помогает новая упаковка, корректировка ценового коридора и более точная работа с целевой аудиторией.'},
        ],
        'en': [
            {'question': 'What do you need before launching a property for sale?', 'answer': 'We need property documents, current photos or access for a shoot, layouts, fee information, management details, encumbrance data, and the owner’s preferred sale scenario.'},
            {'question': 'How long does it take to sell a property?', 'answer': 'There is no fixed timeline. It depends on price, area, property condition, competition, and real demand. We estimate a realistic exposure range before launch and adjust the strategy based on market feedback.'},
            {'question': 'What if my property has already been on the market for a long time?', 'answer': 'We first review pricing, positioning, photos, copy, channels, and lead quality. A stronger package, adjusted price corridor, and clearer buyer targeting often improve the process.'},
        ],
        'th': [
            {'question': 'ต้องเตรียมอะไรบ้างก่อนเริ่มขาย?', 'answer': 'ควรมีเอกสารทรัพย์ รูปปัจจุบันหรือเข้าถึงทรัพย์เพื่อถ่ายภาพ แบบแปลน ข้อมูลค่าใช้จ่าย บริษัทบริหาร ภาระผูกพัน และเป้าหมายการขายของเจ้าของ.'},
            {'question': 'ขายอสังหาริมทรัพย์ใช้เวลานานแค่ไหน?', 'answer': 'ไม่มีระยะเวลาตายตัว ขึ้นอยู่กับราคา ทำเล สภาพทรัพย์ การแข่งขัน และดีมานด์จริง เราจะประเมินกรอบเวลาที่สมเหตุสมผลก่อนเริ่มขายและปรับกลยุทธ์ตาม feedback ตลาด.'},
            {'question': 'ถ้าทรัพย์ขายมานานแล้วยังไม่ปิดดีลควรทำอย่างไร?', 'answer': 'เราจะตรวจราคา positioning รูปภาพ คำอธิบาย ช่องทางการตลาด และคุณภาพลีดก่อน หลายกรณีต้องปรับแพ็กเกจ ราคา และกลุ่มเป้าหมายให้แม่นขึ้น.'},
        ],
    },
    'renting-property': {
        'ru': [
            {'question': 'Почему в каталоге может быть мало объектов аренды?', 'answer': 'Арендный рынок на Пхукете быстро меняется: хорошие варианты часто уходят быстрее, чем успевают попасть в публичный каталог. Поэтому мы дополнительно проверяем партнёрскую базу и актуальность у собственников.'},
            {'question': 'Какой депозит обычно запрашивают собственники?', 'answer': 'Условия депозита зависят от срока аренды, объекта, сезона и требований собственника. До бронирования мы отдельно разбираем сумму депозита, возврат, коммунальные платежи и возможные удержания.'},
            {'question': 'Какие районы лучше подходят для семьи или remote work?', 'answer': 'Для семьи обычно смотрят школы, дорогу, безопасность и инфраструктуру. Для remote work важны интернет, тишина, транспорт и бытовые сервисы. Мы подбираем район под сценарий жизни, а не только под бюджет.'},
        ],
        'en': [
            {'question': 'Why can the rental catalogue have few active listings?', 'answer': 'The Phuket rental market moves quickly, and strong options can disappear before they reach the public catalogue. We also check partner inventory and owner availability directly.'},
            {'question': 'What deposit do owners usually ask for?', 'answer': 'Deposit terms depend on lease length, property, season, and owner requirements. Before reservation we review the deposit amount, return terms, utilities, and possible deductions.'},
            {'question': 'Which areas are better for families or remote work?', 'answer': 'For families we usually check schools, road access, safety, and infrastructure. For remote work, internet, quietness, transport, and daily services matter. We match the area to the living scenario, not only the budget.'},
        ],
        'th': [
            {'question': 'ทำไมในแค็ตตาล็อกเช่าอาจมีรายการน้อย?', 'answer': 'ตลาดเช่าภูเก็ตเปลี่ยนเร็ว ตัวเลือกที่ดีมักถูกจองก่อนขึ้นแค็ตตาล็อกสาธารณะ เราจึงตรวจทั้งฐานพาร์ตเนอร์และความพร้อมจริงกับเจ้าของ.'},
            {'question': 'เจ้าของมักขอเงินประกันเท่าไร?', 'answer': 'เงื่อนไขเงินประกันขึ้นอยู่กับระยะเวลาเช่า ทรัพย์ ฤดูกาล และข้อกำหนดเจ้าของ ก่อนจองเราจะตรวจจำนวนเงินประกัน เงื่อนไขคืน ค่าสาธารณูปโภค และรายการหักที่อาจเกิดขึ้น.'},
            {'question': 'ทำเลไหนเหมาะกับครอบครัวหรือ remote work?', 'answer': 'สำหรับครอบครัวมักดูโรงเรียน การเดินทาง ความปลอดภัย และสิ่งอำนวยความสะดวก ส่วน remote work ต้องดูอินเทอร์เน็ต ความเงียบ การเดินทาง และบริการประจำวัน เราเลือกทำเลตามรูปแบบชีวิต ไม่ใช่แค่งบประมาณ.'},
        ],
    },
    'commercial-real-estate': {
        'ru': [
            {'question': 'Что важно проверить перед покупкой готового бизнеса?', 'answer': 'Смотрим договор аренды или собственность, финансовые вводные, лицензии, персонал, обязательства, сезонность, поток клиентов и причины продажи. Часть проверки требует профильных юридических и бухгалтерских специалистов.'},
            {'question': 'Можно ли оценить окупаемость коммерческого объекта?', 'answer': 'Мы помогаем собрать вводные и построить осторожный сценарий, но не обещаем доходность. Для оценки нужны реальные расходы, аренда, налоги, персонал, сезонность, ремонт и управленческая модель.'},
            {'question': 'Подойдёт ли объект под мой формат бизнеса?', 'answer': 'Это проверяется по локации, трафику, планировке, парковке, инженерии, правилам использования и ограничениям договора. Иногда объект визуально подходит, но не проходит по операционным условиям.'},
        ],
        'en': [
            {'question': 'What should be checked before buying a going concern?', 'answer': 'We review lease or ownership structure, financial inputs, licences, staffing, obligations, seasonality, customer flow, and the seller’s reason for exit. Some checks require specialist legal and accounting support.'},
            {'question': 'Can you estimate commercial payback?', 'answer': 'We help gather inputs and build a cautious scenario, but we do not guarantee returns. A useful review needs real costs, rent, taxes, staffing, seasonality, fit-out needs, and the operating model.'},
            {'question': 'Will a property fit my business format?', 'answer': 'This is checked through location, footfall, layout, parking, utilities, permitted use, and contract restrictions. Sometimes a property looks suitable but fails on operating conditions.'},
        ],
        'th': [
            {'question': 'ก่อนซื้อธุรกิจพร้อมดำเนินการควรตรวจอะไร?', 'answer': 'ควรตรวจโครงสร้างเช่าหรือกรรมสิทธิ์ ข้อมูลการเงิน ใบอนุญาต พนักงาน ภาระผูกพัน ฤดูกาล จำนวนลูกค้า และเหตุผลที่ขาย บางส่วนต้องใช้ผู้เชี่ยวชาญด้านกฎหมายและบัญชี.'},
            {'question': 'ประเมินระยะคืนทุนของทรัพย์เชิงพาณิชย์ได้ไหม?', 'answer': 'เราช่วยรวบรวมข้อมูลและสร้าง scenario แบบระมัดระวัง แต่ไม่รับประกันผลตอบแทน การประเมินต้องดูต้นทุนจริง ค่าเช่า ภาษี พนักงาน ฤดูกาล ค่า fit-out และรูปแบบการบริหาร.'},
            {'question': 'ทรัพย์นี้เหมาะกับรูปแบบธุรกิจของฉันหรือไม่?', 'answer': 'ต้องตรวจทำเล traffic ผังพื้นที่ ที่จอดรถ ระบบวิศวกรรม การใช้ประโยชน์ที่อนุญาต และข้อจำกัดในสัญญา บางทรัพย์ดูเหมาะแต่ไม่ผ่านเงื่อนไขการดำเนินงานจริง.'},
        ],
    },
    'land-sale': {
        'ru': [
            {'question': 'Какие титулы земли стоит проверять в первую очередь?', 'answer': 'В первую очередь смотрят тип правоустанавливающего документа, границы, историю владения и возможность регистрации сделки. Конкретные выводы нужно делать только после проверки документов профильным специалистом.'},
            {'question': 'Можно ли иностранцу купить землю в Таиланде?', 'answer': 'Сделки с землёй для иностранных клиентов требуют отдельной правовой проверки. Мы не советуем полагаться на универсальные схемы и всегда разбираем структуру владения, цель покупки и ограничения до внесения денег.'},
            {'question': 'Что кроме документов влияет на ценность участка?', 'answer': 'Критичны доступ с дороги, рельеф, коммуникации, дренаж, соседняя застройка, назначение земли, вид, шум, расстояние до инфраструктуры и реалистичный сценарий использования.'},
        ],
        'en': [
            {'question': 'Which land title issues should be checked first?', 'answer': 'The first checks usually cover title type, boundaries, ownership history, and whether the transaction can be registered. Final conclusions should only be made after document review by a specialist.'},
            {'question': 'Can a foreigner buy land in Thailand?', 'answer': 'Land transactions for foreign clients require separate legal review. We do not recommend relying on generic structures; ownership route, purchase goal, and restrictions must be checked before any payment.'},
            {'question': 'What affects land value besides documents?', 'answer': 'Road access, topography, utilities, drainage, surrounding development, permitted use, view, noise, distance to infrastructure, and a realistic use scenario all matter.'},
        ],
        'th': [
            {'question': 'ควรตรวจเรื่องเอกสารสิทธิ์ที่ดินอะไรก่อน?', 'answer': 'ควรเริ่มจากประเภทเอกสารสิทธิ์ ขอบเขต ประวัติการถือครอง และความเป็นไปได้ในการจดทะเบียนดีล ข้อสรุปควรทำหลังผู้เชี่ยวชาญตรวจเอกสารแล้วเท่านั้น.'},
            {'question': 'ชาวต่างชาติซื้อที่ดินในไทยได้ไหม?', 'answer': 'ดีลที่ดินสำหรับลูกค้าต่างชาติต้องตรวจด้านกฎหมายแยกต่างหาก เราไม่แนะนำให้ใช้โครงสร้างทั่วไปโดยไม่ตรวจ ต้องดูโครงสร้างการถือครอง เป้าหมาย และข้อจำกัดก่อนชำระเงิน.'},
            {'question': 'นอกจากเอกสารแล้วอะไรมีผลต่อมูลค่าที่ดิน?', 'answer': 'ทางเข้าออก ลักษณะพื้นที่ สาธารณูปโภค การระบายน้ำ สิ่งปลูกสร้างรอบข้าง การใช้ประโยชน์ วิว เสียงรบกวน ระยะถึงโครงสร้างพื้นฐาน และ scenario การใช้งานที่เป็นจริงล้วนสำคัญ.'},
        ],
    },
    'legal-services': {
        'ru': [
            {'question': 'На каком этапе лучше подключать юридическую проверку?', 'answer': 'Лучше до внесения существенных платежей и до подписания документов, которые фиксируют обязательства. Чем раньше видна структура сделки, тем проще скорректировать рисковые условия.'},
            {'question': 'Что проверяется в reservation agreement или SPA?', 'answer': 'Смотрим стороны сделки, объект, цену, график платежей, штрафы, сроки, условия возврата, передачу объекта, приложения и обязательства сторон. При необходимости подключаем профильных юристов.'},
            {'question': 'Можете ли вы проверить застройщика или продавца?', 'answer': 'Мы помогаем собрать и проверить доступные вводные по стороне сделки, документам и истории объекта. Это не заменяет юридическое заключение, но помогает понять, какие вопросы нужно закрыть до оплаты.'},
        ],
        'en': [
            {'question': 'When should legal review be involved?', 'answer': 'Ideally before major payments and before signing documents that create binding obligations. The earlier the deal structure is visible, the easier it is to adjust risky terms.'},
            {'question': 'What do you check in a reservation agreement or SPA?', 'answer': 'We review parties, property details, price, payment schedule, penalties, deadlines, refund terms, handover, annexes, and party obligations. Specialist lawyers are involved where needed.'},
            {'question': 'Can you check the developer or seller?', 'answer': 'We help gather and review available information about the counterparty, documents, and property history. This does not replace a legal opinion, but it shows which questions must be closed before payment.'},
        ],
        'th': [
            {'question': 'ควรเริ่มตรวจด้านกฎหมายเมื่อไร?', 'answer': 'ควรเริ่มก่อนชำระเงินจำนวนมากและก่อนลงนามเอกสารที่สร้างภาระผูกพัน ยิ่งเห็นโครงสร้างดีลเร็วเท่าไร ก็ยิ่งปรับเงื่อนไขเสี่ยงได้ง่ายขึ้น.'},
            {'question': 'ตรวจอะไรใน reservation agreement หรือ SPA?', 'answer': 'เราตรวจคู่สัญญา รายละเอียดทรัพย์ ราคา ตารางชำระเงิน ค่าปรับ กำหนดเวลา เงื่อนไขคืนเงิน การส่งมอบ ภาคผนวก และภาระของแต่ละฝ่าย และประสานผู้เชี่ยวชาญด้านกฎหมายเมื่อจำเป็น.'},
            {'question': 'ช่วยตรวจผู้พัฒนาหรือผู้ขายได้ไหม?', 'answer': 'เราช่วยรวบรวมและตรวจข้อมูลที่มีเกี่ยวกับคู่สัญญา เอกสาร และประวัติทรัพย์ งานนี้ไม่แทน legal opinion แต่ช่วยระบุคำถามที่ต้องปิดก่อนชำระเงิน.'},
        ],
    },
}


SECTION_LABELS = {
    'ru': {
        'services_menu': 'Наши услуги',
        'contact_form': 'Получить консультацию',
        'contact_form_text': 'Оставьте заявку и наш специалист свяжется с вами в течение часа',
        'name_placeholder': 'Ваше имя',
        'phone_placeholder': 'Телефон',
        'email_placeholder': 'Email',
        'message_placeholder': 'Ваш вопрос',
        'submit': 'Отправить заявку',
        'privacy_prefix': 'Нажимая кнопку, вы соглашаетесь с',
        'privacy_label': 'политикой конфиденциальности',
        'featured_title': 'Рекомендуемые объекты',
        'featured_subtitle': 'Недвижимость, которая может вас заинтересовать',
        'details': 'Подробнее',
        'all_properties': 'Смотреть все объекты',
        'start_title': 'Готовы начать?',
        'start_text': 'Свяжитесь с нами прямо сейчас для получения персональной консультации по',
        'contact_us': 'Связаться с нами',
        'call': 'Позвонить',
        'content_fallback_title': 'Подробно об услуге',
        'service_faq_heading': 'Частые вопросы по услуге',
        'cases_heading': 'Практические кейсы',
    },
    'en': {
        'services_menu': 'Our services',
        'contact_form': 'Request a consultation',
        'contact_form_text': 'Leave a request and our specialist will contact you within the hour',
        'name_placeholder': 'Your name',
        'phone_placeholder': 'Phone',
        'email_placeholder': 'Email',
        'message_placeholder': 'Your question',
        'submit': 'Send request',
        'privacy_prefix': 'By clicking the button you agree to the',
        'privacy_label': 'privacy policy',
        'featured_title': 'Recommended properties',
        'featured_subtitle': 'Properties that may suit your goals',
        'details': 'Learn more',
        'all_properties': 'View all properties',
        'start_title': 'Ready to move forward?',
        'start_text': 'Contact us now for a personalised consultation on',
        'contact_us': 'Contact us',
        'call': 'Call us',
        'content_fallback_title': 'Service overview',
        'service_faq_heading': 'Frequently asked questions',
        'cases_heading': 'Selected cases',
    },
    'th': {
        'services_menu': 'บริการของเรา',
        'contact_form': 'ขอคำปรึกษา',
        'contact_form_text': 'ฝากข้อมูลไว้ แล้วผู้เชี่ยวชาญของเราจะติดต่อกลับภายใน 1 ชั่วโมง',
        'name_placeholder': 'ชื่อของคุณ',
        'phone_placeholder': 'โทรศัพท์',
        'email_placeholder': 'อีเมล',
        'message_placeholder': 'คำถามของคุณ',
        'submit': 'ส่งคำขอ',
        'privacy_prefix': 'เมื่อกดปุ่มนี้ คุณยอมรับ',
        'privacy_label': 'นโยบายความเป็นส่วนตัว',
        'featured_title': 'ทรัพย์แนะนำ',
        'featured_subtitle': 'อสังหาริมทรัพย์ที่อาจเหมาะกับเป้าหมายของคุณ',
        'details': 'ดูรายละเอียด',
        'all_properties': 'ดูอสังหาริมทรัพย์ทั้งหมด',
        'start_title': 'พร้อมเริ่มต้นแล้วหรือยัง?',
        'start_text': 'ติดต่อเราเพื่อรับคำปรึกษาเฉพาะด้านเกี่ยวกับ',
        'contact_us': 'ติดต่อเรา',
        'call': 'โทรหาเรา',
        'content_fallback_title': 'ภาพรวมของบริการ',
        'service_faq_heading': 'คำถามที่พบบ่อย',
        'cases_heading': 'ตัวอย่างเคส',
    },
}


SERVICE_PAGE_COPY = {
    'buying-property': {
        'ru': {
            'title': 'Покупка недвижимости',
            'description': 'Подбор объектов, проверка документов, переговоры и сопровождение сделки для безопасной покупки недвижимости на Пхукете.',
        },
        'en': {
            'title': 'Purchase of real estate',
            'description': 'Property selection, document review, negotiation, and full transaction support for a safe real estate purchase in Phuket.',
        },
        'th': {
            'title': 'บริการซื้ออสังหาริมทรัพย์',
            'description': 'บริการคัดเลือกทรัพย์ ตรวจเอกสาร เจรจา และดูแลธุรกรรมอย่างครบถ้วนเพื่อการซื้ออสังหาริมทรัพย์ในภูเก็ตอย่างปลอดภัย.',
        },
    },
    'selling-property': {
        'ru': {
            'title': 'Продажа недвижимости',
            'description': 'Оценка, упаковка объекта, маркетинг, показы и переговоры для продажи недвижимости по рыночной стратегии.',
        },
        'en': {
            'title': 'Sale of real estate',
            'description': 'Pricing strategy, packaging, marketing, viewings, and negotiation support to sell real estate with a clear market plan.',
        },
        'th': {
            'title': 'บริการขายอสังหาริมทรัพย์',
            'description': 'ประเมินราคา วางกลยุทธ์การตลาด จัดการการพาชม และเจรจาเพื่อขายอสังหาริมทรัพย์อย่างเป็นระบบ.',
        },
    },
    'renting-property': {
        'ru': {
            'title': 'Аренда недвижимости',
            'description': 'Подбор аренды, проверка условий, сопровождение договора и заселения для long stay и short stay на Пхукете.',
        },
        'en': {
            'title': 'Rental of real estate',
            'description': 'Rental sourcing, term review, agreement support, and move-in coordination for long-stay and short-stay property in Phuket.',
        },
        'th': {
            'title': 'บริการเช่าอสังหาริมทรัพย์',
            'description': 'ช่วยคัดเลือกทรัพย์เช่า ตรวจเงื่อนไขสัญญา และดูแลขั้นตอนย้ายเข้า สำหรับการเช่าระยะสั้นและระยะยาวในภูเก็ต.',
        },
    },
    'land-sale': {
        'ru': {
            'title': 'Продажа земли',
            'description': 'Подбор участков, проверка статуса земли, оценка рисков и сопровождение сделок с земельными активами на Пхукете и рядом.',
        },
        'en': {
            'title': 'Land sale',
            'description': 'Land sourcing, title review, risk assessment, and support for land transactions in Phuket and nearby provinces.',
        },
        'th': {
            'title': 'บริการซื้อขายที่ดิน',
            'description': 'ช่วยคัดเลือกที่ดิน ตรวจสอบสถานะเอกสาร ประเมินความเสี่ยง และดูแลธุรกรรมที่ดินในภูเก็ตและจังหวัดใกล้เคียง.',
        },
    },
    'commercial-real-estate': {
        'ru': {
            'title': 'Коммерческая недвижимость',
            'description': 'Подбор коммерческих объектов и готового бизнеса, проверка условий сделки и оценка операционных рисков.',
        },
        'en': {
            'title': 'Commercial real estate',
            'description': 'Selection of commercial property and business assets, transaction review, and evaluation of operating risks.',
        },
        'th': {
            'title': 'บริการอสังหาริมทรัพย์เชิงพาณิชย์',
            'description': 'ช่วยคัดเลือกอสังหาริมทรัพย์เชิงพาณิชย์และธุรกิจพร้อมดำเนินการ พร้อมตรวจสอบดีลและประเมินความเสี่ยงการดำเนินงาน.',
        },
    },
    'legal-services': {
        'ru': {
            'title': 'Юридические услуги',
            'description': 'Проверка договоров, анализ рисков, сопровождение расчётов и безопасная структура сделок с недвижимостью.',
        },
        'en': {
            'title': 'Legal services',
            'description': 'Contract review, risk analysis, transaction structuring, and legal support for safer real estate deals.',
        },
        'th': {
            'title': 'บริการด้านกฎหมาย',
            'description': 'ตรวจสัญญา วิเคราะห์ความเสี่ยง จัดโครงสร้างธุรกรรม และดูแลด้านกฎหมายเพื่อให้ดีลอสังหาริมทรัพย์ปลอดภัยมากขึ้น.',
        },
    },
}


def build_service_landing_content(service_slug, language_code='ru'):
    language_code = (language_code or 'ru')[:2]
    service_content = SERVICE_LANDING_CONTENT.get(service_slug, {})
    localized = service_content.get(language_code) or service_content.get('ru')
    if not localized:
        return {}

    payload = deepcopy(localized)
    faq_extensions = SERVICE_FAQ_EXTENSIONS.get(service_slug, {})
    extra_faq = faq_extensions.get(language_code) or faq_extensions.get('ru') or []
    if extra_faq:
        payload['faq'] = payload.get('faq', []) + deepcopy(extra_faq)
    payload['labels'] = SECTION_LABELS.get(language_code, SECTION_LABELS['ru'])
    return payload


def get_service_page_copy(service_slug, language_code='ru'):
    language_code = (language_code or 'ru')[:2]
    service_copy = SERVICE_PAGE_COPY.get(service_slug, {})
    return service_copy.get(language_code) or service_copy.get('ru') or {}
